/**
 * 원페이지 템플릿 데이터
 * 100+ 비즈니스 유형별 템플릿 정의
 */

import type { BusinessInfo, ServiceItem, TestimonialItem, GalleryItem, HeroProps } from './OnepageBase'

// 템플릿 카테고리
export type OnepageCategory =
  | 'professional'   // 전문직 (변호사, 의사, 회계사 등)
  | 'education'      // 교육 (학원, 과외, 코칭 등)
  | 'beauty'         // 뷰티 (헤어샵, 네일, 피부관리 등)
  | 'food'           // 요식업 (카페, 레스토랑, 베이커리 등)
  | 'health'         // 건강/운동 (헬스장, 요가, 필라테스 등)
  | 'realestate'     // 부동산 (중개, 인테리어, 청소 등)
  | 'event'          // 이벤트 (웨딩, 파티, 촬영 등)
  | 'tech'           // IT/테크 (개발, 디자인, 마케팅 등)
  | 'service'        // 서비스업 (세차, 이사, 수리 등)
  | 'retail'         // 소매 (의류, 잡화, 꽃 등)
  | 'art'            // 예술 (음악, 미술, 공예 등)
  | 'pet'            // 반려동물 (펫샵, 미용, 호텔 등)
  | 'travel'         // 여행 (숙박, 투어, 렌탈 등)
  | 'consulting'     // 컨설팅 (경영, 세무, 법률 등)
  | 'personal'       // 개인 (포트폴리오, 이력서 등)

// 템플릿 메타데이터
export interface OnepageTemplateMeta {
  id: string
  name: string
  nameEn: string
  category: OnepageCategory
  description: string
  icon: string
  defaultHero: HeroProps
  defaultBusiness: Partial<BusinessInfo>
  defaultServices: ServiceItem[]
  keywords: string[]
}

// 100+ 템플릿 정의
export const ONEPAGE_TEMPLATES: OnepageTemplateMeta[] = [
  // ==================== 전문직 (20개) ====================
  {
    id: 'lawyer',
    name: '변호사/로펌',
    nameEn: 'Law Firm',
    category: 'professional',
    description: '법률 사무소, 변호사 소개 페이지',
    icon: '⚖️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1920',
      overlayOpacity: 60,
      title: '당신의 권리를\n지켜드립니다',
      subtitle: '20년 경력의 전문 법률팀이 함께합니다',
      primaryCTA: { label: '무료 상담 신청', href: '#contact' },
    },
    defaultBusiness: {
      name: '정의 법률사무소',
      tagline: '민사, 형사, 가사 전문',
    },
    defaultServices: [
      { emoji: '📋', title: '민사 소송', description: '계약, 손해배상, 부동산 분쟁' },
      { emoji: '⚖️', title: '형사 변호', description: '수사 대응, 재판 변론' },
      { emoji: '👨‍👩‍👧', title: '가사/이혼', description: '이혼, 양육권, 재산분할' },
      { emoji: '🏢', title: '기업 자문', description: '계약서 검토, 법률 자문' },
    ],
    keywords: ['법률', '변호사', '소송', '로펌'],
  },
  {
    id: 'doctor-clinic',
    name: '병원/의원',
    nameEn: 'Medical Clinic',
    category: 'professional',
    description: '병원, 의원, 클리닉 소개 페이지',
    icon: '🏥',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1920',
      overlayOpacity: 50,
      title: '건강한 삶을 위한\n첫걸음',
      subtitle: '친절한 진료, 정확한 진단',
      primaryCTA: { label: '진료 예약', href: '#contact' },
    },
    defaultBusiness: {
      name: '행복 내과의원',
      tagline: '내과 전문의 직접 진료',
    },
    defaultServices: [
      { emoji: '🩺', title: '일반 내과', description: '감기, 소화기, 호흡기 질환' },
      { emoji: '💉', title: '예방 접종', description: '독감, 폐렴, 대상포진' },
      { emoji: '📊', title: '건강검진', description: '종합검진, 직장검진' },
      { emoji: '💊', title: '만성질환', description: '당뇨, 고혈압, 고지혈증' },
    ],
    keywords: ['병원', '의원', '클리닉', '진료'],
  },
  {
    id: 'dentist',
    name: '치과',
    nameEn: 'Dental Clinic',
    category: 'professional',
    description: '치과 병원 소개 페이지',
    icon: '🦷',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1920',
      overlayOpacity: 50,
      title: '아름다운 미소를\n디자인합니다',
      subtitle: '최신 장비, 무통 치료',
      primaryCTA: { label: '상담 예약', href: '#contact' },
    },
    defaultBusiness: { name: '스마일 치과', tagline: '치아 교정, 임플란트 전문' },
    defaultServices: [
      { emoji: '✨', title: '치아 미백', description: '전문가 미백, 셀프 미백' },
      { emoji: '🦷', title: '임플란트', description: '네비게이션 임플란트' },
      { emoji: '📐', title: '치아 교정', description: '투명 교정, 설측 교정' },
      { emoji: '🛡️', title: '일반 진료', description: '충치, 잇몸, 스케일링' },
    ],
    keywords: ['치과', '임플란트', '교정', '치아미백'],
  },
  {
    id: 'psychiatrist',
    name: '정신건강의학과',
    nameEn: 'Psychiatry',
    category: 'professional',
    description: '정신과, 심리상담 소개 페이지',
    icon: '🧠',
    defaultHero: {
      type: 'gradient',
      overlayOpacity: 30,
      title: '마음의 평화를\n되찾으세요',
      subtitle: '전문 상담사가 함께합니다',
      primaryCTA: { label: '비밀 상담', href: '#contact' },
    },
    defaultBusiness: { name: '마음치유 클리닉', tagline: '우울증, 불안장애 전문' },
    defaultServices: [
      { emoji: '💭', title: '심리 상담', description: '개인/커플 상담' },
      { emoji: '🧘', title: '스트레스 관리', description: '직장, 학업 스트레스' },
      { emoji: '😴', title: '수면 장애', description: '불면증, 수면무호흡' },
      { emoji: '💔', title: '우울/불안', description: '우울증, 공황장애' },
    ],
    keywords: ['정신과', '상담', '심리치료', '우울증'],
  },
  {
    id: 'accountant',
    name: '회계사/세무사',
    nameEn: 'Accounting',
    category: 'professional',
    description: '회계/세무 사무소 소개 페이지',
    icon: '📊',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '세금 걱정은\n저희에게 맡기세요',
      subtitle: '합법적인 절세 방법을 찾아드립니다',
      primaryCTA: { label: '무료 상담', href: '#contact' },
    },
    defaultBusiness: { name: '든든 세무회계', tagline: '중소기업 전문 세무사' },
    defaultServices: [
      { emoji: '📝', title: '기장 대리', description: '매월 기장, 재무제표' },
      { emoji: '💰', title: '세금 신고', description: '법인세, 소득세, 부가세' },
      { emoji: '🏢', title: '법인 설립', description: '사업자 등록, 정관 작성' },
      { emoji: '📈', title: '절세 컨설팅', description: '합법적 절세 전략' },
    ],
    keywords: ['세무사', '회계사', '세금', '기장'],
  },
  {
    id: 'patent-attorney',
    name: '변리사/특허',
    nameEn: 'Patent Attorney',
    category: 'professional',
    description: '특허/상표 사무소 소개 페이지',
    icon: '💡',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '아이디어를\n권리로 만듭니다',
      subtitle: '특허, 상표, 디자인 출원 전문',
      primaryCTA: { label: '무료 검토', href: '#contact' },
    },
    defaultBusiness: { name: '아이디어 특허사무소', tagline: '스타트업 전문' },
    defaultServices: [
      { emoji: '💡', title: '특허 출원', description: '발명 특허, 실용신안' },
      { emoji: '®️', title: '상표 등록', description: '브랜드, 로고 보호' },
      { emoji: '🎨', title: '디자인 등록', description: '제품 디자인 보호' },
      { emoji: '⚔️', title: '분쟁 대리', description: '침해소송, 무효심판' },
    ],
    keywords: ['특허', '변리사', '상표', '지식재산권'],
  },
  {
    id: 'veterinary',
    name: '동물병원',
    nameEn: 'Veterinary',
    category: 'professional',
    description: '동물병원 소개 페이지',
    icon: '🐕',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=1920',
      overlayOpacity: 50,
      title: '사랑하는 가족의\n건강을 지킵니다',
      subtitle: '24시 응급진료, 전문 수의사',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '사랑 동물병원', tagline: '강아지/고양이 전문' },
    defaultServices: [
      { emoji: '🩺', title: '건강검진', description: '정기 건강검진, 예방접종' },
      { emoji: '🏥', title: '내과/외과', description: '질병 치료, 수술' },
      { emoji: '🦷', title: '치과', description: '스케일링, 발치' },
      { emoji: '✂️', title: '미용', description: '목욕, 미용 서비스' },
    ],
    keywords: ['동물병원', '수의사', '반려동물', '펫'],
  },
  {
    id: 'real-estate-agent',
    name: '공인중개사',
    nameEn: 'Real Estate',
    category: 'professional',
    description: '부동산 중개 소개 페이지',
    icon: '🏠',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1920',
      overlayOpacity: 50,
      title: '당신의 새 보금자리를\n찾아드립니다',
      subtitle: '정직한 중개, 안전한 거래',
      primaryCTA: { label: '매물 문의', href: '#contact' },
    },
    defaultBusiness: { name: '행복 부동산', tagline: '아파트, 상가 전문' },
    defaultServices: [
      { emoji: '🏢', title: '아파트', description: '매매, 전세, 월세' },
      { emoji: '🏪', title: '상가/오피스', description: '임대, 매매' },
      { emoji: '🏘️', title: '빌라/주택', description: '원룸, 투룸, 단독주택' },
      { emoji: '📊', title: '시세 분석', description: '투자 상담, 시세 정보' },
    ],
    keywords: ['부동산', '공인중개사', '아파트', '매매'],
  },
  {
    id: 'architect',
    name: '건축사/설계',
    nameEn: 'Architect',
    category: 'professional',
    description: '건축 설계 사무소 소개 페이지',
    icon: '🏗️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1920',
      overlayOpacity: 50,
      title: '공간의 꿈을\n설계합니다',
      subtitle: '주거, 상업, 공공 건축 전문',
      primaryCTA: { label: '프로젝트 문의', href: '#contact' },
    },
    defaultBusiness: { name: '드림 건축사사무소', tagline: '친환경 건축 설계' },
    defaultServices: [
      { emoji: '🏠', title: '주택 설계', description: '단독주택, 다가구' },
      { emoji: '🏢', title: '상업 건축', description: '상가, 오피스빌딩' },
      { emoji: '🔧', title: '리모델링', description: '증축, 대수선' },
      { emoji: '🌿', title: '인테리어', description: '실내 설계, 가구 배치' },
    ],
    keywords: ['건축', '설계', '건축사', '리모델링'],
  },
  {
    id: 'pharmacist',
    name: '약국',
    nameEn: 'Pharmacy',
    category: 'professional',
    description: '약국 소개 페이지',
    icon: '💊',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '건강한 삶의\n파트너',
      subtitle: '전문 약사의 친절한 상담',
      primaryCTA: { label: '상담 문의', href: '#contact' },
    },
    defaultBusiness: { name: '온누리 약국', tagline: '조제, 건강기능식품 전문' },
    defaultServices: [
      { emoji: '💊', title: '처방 조제', description: '신속 정확한 조제' },
      { emoji: '🍀', title: '건강식품', description: '비타민, 영양제' },
      { emoji: '🩹', title: '의약외품', description: '상비약, 밴드' },
      { emoji: '👴', title: '복약 상담', description: '맞춤 건강 상담' },
    ],
    keywords: ['약국', '약사', '조제', '건강식품'],
  },

  // ==================== 교육 (15개) ====================
  {
    id: 'academy-english',
    name: '영어학원',
    nameEn: 'English Academy',
    category: 'education',
    description: '영어 학원 소개 페이지',
    icon: '🇺🇸',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1920',
      overlayOpacity: 50,
      title: '영어 실력\n확실하게 올려드립니다',
      subtitle: '원어민 강사, 소수정예 수업',
      primaryCTA: { label: '무료 레벨테스트', href: '#contact' },
    },
    defaultBusiness: { name: '스피킹 영어학원', tagline: '회화, 토익, 토플 전문' },
    defaultServices: [
      { emoji: '🗣️', title: '회화 과정', description: '원어민 프리토킹' },
      { emoji: '📚', title: 'TOEIC/TOEFL', description: '고득점 보장반' },
      { emoji: '👶', title: '주니어 영어', description: '파닉스, 스토리북' },
      { emoji: '💼', title: '비즈니스 영어', description: '직장인 회화' },
    ],
    keywords: ['영어학원', '토익', '회화', '영어'],
  },
  {
    id: 'academy-math',
    name: '수학학원',
    nameEn: 'Math Academy',
    category: 'education',
    description: '수학 학원 소개 페이지',
    icon: '🔢',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '수학이 쉬워지는\n마법의 시작',
      subtitle: '개념부터 심화까지 완벽 정복',
      primaryCTA: { label: '상담 신청', href: '#contact' },
    },
    defaultBusiness: { name: '수학의 정석 학원', tagline: '초중고 내신/수능 전문' },
    defaultServices: [
      { emoji: '📐', title: '초등 수학', description: '기초 연산, 도형' },
      { emoji: '📊', title: '중등 수학', description: '내신 대비, 선행' },
      { emoji: '📈', title: '고등 수학', description: '수능, 내신 완성' },
      { emoji: '🏆', title: '경시반', description: 'KMO, 영재원 대비' },
    ],
    keywords: ['수학학원', '내신', '수능', '수학'],
  },
  {
    id: 'coding-academy',
    name: '코딩학원',
    nameEn: 'Coding Academy',
    category: 'education',
    description: '코딩/프로그래밍 학원 소개 페이지',
    icon: '💻',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1920',
      overlayOpacity: 60,
      title: '미래를 코딩하는\n아이들',
      subtitle: '창의력과 논리력을 키우는 코딩 교육',
      primaryCTA: { label: '무료 체험', href: '#contact' },
    },
    defaultBusiness: { name: '코드랩 아카데미', tagline: '어린이/청소년 코딩 전문' },
    defaultServices: [
      { emoji: '🎮', title: '스크래치', description: '초등 기초 코딩' },
      { emoji: '🐍', title: '파이썬', description: '중등 텍스트 코딩' },
      { emoji: '🤖', title: 'AI/로봇', description: '인공지능, 로봇 코딩' },
      { emoji: '🎨', title: '앱 개발', description: '앱 인벤터, 플러터' },
    ],
    keywords: ['코딩학원', '프로그래밍', '코딩교육', 'SW'],
  },
  {
    id: 'music-school',
    name: '음악학원/피아노',
    nameEn: 'Music School',
    category: 'education',
    description: '음악/피아노 학원 소개 페이지',
    icon: '🎹',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1920',
      overlayOpacity: 50,
      title: '음악과 함께하는\n행복한 성장',
      subtitle: '1:1 맞춤 레슨, 콩쿠르 대비',
      primaryCTA: { label: '체험 레슨', href: '#contact' },
    },
    defaultBusiness: { name: '도레미 음악학원', tagline: '피아노, 바이올린, 첼로 전문' },
    defaultServices: [
      { emoji: '🎹', title: '피아노', description: '클래식, 재즈, 반주' },
      { emoji: '🎻', title: '현악기', description: '바이올린, 첼로' },
      { emoji: '🎸', title: '기타', description: '통기타, 일렉기타' },
      { emoji: '🎤', title: '보컬', description: '발성, 노래' },
    ],
    keywords: ['음악학원', '피아노', '바이올린', '악기'],
  },
  {
    id: 'art-studio',
    name: '미술학원',
    nameEn: 'Art Studio',
    category: 'education',
    description: '미술 학원/스튜디오 소개 페이지',
    icon: '🎨',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1920',
      overlayOpacity: 50,
      title: '창의력이 자라는\n예술의 공간',
      subtitle: '아동미술부터 입시미술까지',
      primaryCTA: { label: '상담 예약', href: '#contact' },
    },
    defaultBusiness: { name: '아뜰리에 미술학원', tagline: '아동미술, 입시미술 전문' },
    defaultServices: [
      { emoji: '🖍️', title: '아동미술', description: '창의미술, 기초드로잉' },
      { emoji: '🖌️', title: '취미미술', description: '수채화, 유화, 아크릴' },
      { emoji: '📝', title: '입시미술', description: '기초디자인, 사고의전환' },
      { emoji: '💻', title: '디지털아트', description: '아이패드 드로잉' },
    ],
    keywords: ['미술학원', '아동미술', '입시미술', '그림'],
  },
  {
    id: 'taekwondo',
    name: '태권도장',
    nameEn: 'Taekwondo',
    category: 'education',
    description: '태권도장 소개 페이지',
    icon: '🥋',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=1920',
      overlayOpacity: 50,
      title: '몸과 마음을\n함께 키우는 수련',
      subtitle: '예절, 체력, 자신감 UP!',
      primaryCTA: { label: '무료 체험', href: '#contact' },
    },
    defaultBusiness: { name: '정도 태권도장', tagline: '세계태권도연맹 공인' },
    defaultServices: [
      { emoji: '👶', title: '유아반', description: '5-7세 기초 체력' },
      { emoji: '🧒', title: '초등반', description: '품새, 겨루기' },
      { emoji: '🏋️', title: '성인반', description: '호신술, 다이어트' },
      { emoji: '🏆', title: '선수반', description: '대회 출전 준비' },
    ],
    keywords: ['태권도', '무술', '체력', '호신술'],
  },
  {
    id: 'driving-school',
    name: '운전학원',
    nameEn: 'Driving School',
    category: 'education',
    description: '운전 학원 소개 페이지',
    icon: '🚗',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1920',
      overlayOpacity: 50,
      title: '안전운전의\n첫 시작',
      subtitle: '친절한 교육, 높은 합격률',
      primaryCTA: { label: '등록 문의', href: '#contact' },
    },
    defaultBusiness: { name: '스마트 운전학원', tagline: '1종, 2종 보통/자동' },
    defaultServices: [
      { emoji: '🚗', title: '2종 자동', description: '승용차 AT' },
      { emoji: '🚙', title: '2종 보통', description: '승용차 MT' },
      { emoji: '🚌', title: '1종 보통', description: '화물, 버스' },
      { emoji: '🏍️', title: '2종 소형', description: '오토바이' },
    ],
    keywords: ['운전학원', '면허', '자동차', '운전'],
  },
  {
    id: 'language-school',
    name: '외국어학원',
    nameEn: 'Language School',
    category: 'education',
    description: '외국어(일본어, 중국어 등) 학원 소개',
    icon: '🌏',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '세계와 소통하는\n언어의 힘',
      subtitle: '일본어, 중국어, 스페인어 전문',
      primaryCTA: { label: '무료 상담', href: '#contact' },
    },
    defaultBusiness: { name: '글로벌 어학원', tagline: 'JLPT, HSK 전문' },
    defaultServices: [
      { emoji: '🇯🇵', title: '일본어', description: 'JLPT, 회화, 비즈니스' },
      { emoji: '🇨🇳', title: '중국어', description: 'HSK, 회화, 비즈니스' },
      { emoji: '🇪🇸', title: '스페인어', description: 'DELE, 여행 회화' },
      { emoji: '🇫🇷', title: '프랑스어', description: 'DELF, 기초 회화' },
    ],
    keywords: ['외국어', '일본어', '중국어', '어학원'],
  },

  // ==================== 뷰티 (12개) ====================
  {
    id: 'hair-salon',
    name: '헤어샵/미용실',
    nameEn: 'Hair Salon',
    category: 'beauty',
    description: '헤어샵/미용실 소개 페이지',
    icon: '💇',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1920',
      overlayOpacity: 50,
      title: '당신만의 스타일을\n완성합니다',
      subtitle: '트렌디한 헤어 디자인',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '아뜰리에 헤어', tagline: '컷, 펌, 염색 전문' },
    defaultServices: [
      { emoji: '✂️', title: '커트', description: '여성/남성 헤어컷' },
      { emoji: '💈', title: '펌', description: '디지털펌, 셋팅펌' },
      { emoji: '🎨', title: '염색', description: '매니큐어, 풀염색' },
      { emoji: '✨', title: '클리닉', description: '손상모 케어' },
    ],
    keywords: ['미용실', '헤어샵', '커트', '펌'],
  },
  {
    id: 'nail-shop',
    name: '네일샵',
    nameEn: 'Nail Shop',
    category: 'beauty',
    description: '네일아트 샵 소개 페이지',
    icon: '💅',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1920',
      overlayOpacity: 50,
      title: '손끝에서\n피어나는 아름다움',
      subtitle: '젤네일, 아트네일 전문',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '네일아뜨', tagline: '젤네일, 패디 전문' },
    defaultServices: [
      { emoji: '💅', title: '젤네일', description: '원컬러, 프렌치' },
      { emoji: '🎨', title: '아트네일', description: '시즌아트, 캐릭터' },
      { emoji: '🦶', title: '페디큐어', description: '각질제거, 젤페디' },
      { emoji: '✨', title: '네일케어', description: '손톱 관리, 큐티클' },
    ],
    keywords: ['네일샵', '젤네일', '네일아트', '페디큐어'],
  },
  {
    id: 'skincare',
    name: '피부관리샵',
    nameEn: 'Skincare',
    category: 'beauty',
    description: '피부관리실 소개 페이지',
    icon: '✨',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1920',
      overlayOpacity: 50,
      title: '건강한 피부\n아름다운 당신',
      subtitle: '프리미엄 피부 관리',
      primaryCTA: { label: '상담 예약', href: '#contact' },
    },
    defaultBusiness: { name: '글로우업 에스테틱', tagline: '피부관리, 바디케어 전문' },
    defaultServices: [
      { emoji: '✨', title: '기본관리', description: '클렌징, 영양관리' },
      { emoji: '💆', title: '스페셜관리', description: '리프팅, 미백' },
      { emoji: '🌟', title: '여드름관리', description: '압출, 진정케어' },
      { emoji: '💫', title: '안티에이징', description: '주름, 탄력 케어' },
    ],
    keywords: ['피부관리', '에스테틱', '스킨케어', '마사지'],
  },
  {
    id: 'makeup-studio',
    name: '메이크업샵',
    nameEn: 'Makeup Studio',
    category: 'beauty',
    description: '메이크업 스튜디오 소개 페이지',
    icon: '💄',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1920',
      overlayOpacity: 50,
      title: '특별한 날의\n완벽한 메이크업',
      subtitle: '웨딩, 프로필, 이벤트 메이크업',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '블로썸 메이크업', tagline: '웨딩, 프로필 전문' },
    defaultServices: [
      { emoji: '💒', title: '웨딩', description: '신부, 혼주 메이크업' },
      { emoji: '📸', title: '프로필', description: '증명사진, 프로필' },
      { emoji: '🎭', title: '특수', description: '무대, 촬영 메이크업' },
      { emoji: '👰', title: '레슨', description: '셀프메이크업 강습' },
    ],
    keywords: ['메이크업', '웨딩', '프로필', '화장'],
  },
  {
    id: 'spa-massage',
    name: '스파/마사지',
    nameEn: 'Spa & Massage',
    category: 'beauty',
    description: '스파/마사지샵 소개 페이지',
    icon: '🧖',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1920',
      overlayOpacity: 50,
      title: '일상의 피로를\n녹여드립니다',
      subtitle: '힐링 마사지, 아로마 테라피',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '릴렉스 스파', tagline: '타이마사지, 아로마 전문' },
    defaultServices: [
      { emoji: '🧘', title: '타이마사지', description: '전신 스트레칭' },
      { emoji: '🌸', title: '아로마', description: '오일 마사지' },
      { emoji: '🦶', title: '발마사지', description: '발 경락, 반사요법' },
      { emoji: '💆', title: '헤드스파', description: '두피 마사지' },
    ],
    keywords: ['스파', '마사지', '타이마사지', '아로마'],
  },

  // ==================== 요식업 (15개) ====================
  {
    id: 'cafe',
    name: '카페',
    nameEn: 'Cafe',
    category: 'food',
    description: '카페 소개 페이지',
    icon: '☕',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1920',
      overlayOpacity: 40,
      title: '커피 한 잔의\n여유',
      subtitle: '스페셜티 커피, 수제 디저트',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '모먼트 커피', tagline: '스페셜티 커피 전문점' },
    defaultServices: [
      { emoji: '☕', title: '시그니처', description: '하우스 블렌드', price: '5,500원' },
      { emoji: '🥛', title: '라떼', description: '부드러운 우유 라떼', price: '6,000원' },
      { emoji: '🧁', title: '디저트', description: '수제 케이크, 쿠키', price: '5,000원~' },
      { emoji: '🍵', title: '티/음료', description: '녹차, 과일음료', price: '5,500원~' },
    ],
    keywords: ['카페', '커피', '커피숍', '디저트'],
  },
  {
    id: 'restaurant-korean',
    name: '한식당',
    nameEn: 'Korean Restaurant',
    category: 'food',
    description: '한식 레스토랑 소개 페이지',
    icon: '🍚',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1580651315530-69c8e0026377?w=1920',
      overlayOpacity: 50,
      title: '정성을 담은\n한 상 차림',
      subtitle: '전통 가정식, 정갈한 한식',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '시골밥상', tagline: '정통 가정식 전문점' },
    defaultServices: [
      { emoji: '🍚', title: '정식', description: '제육정식, 생선정식', price: '12,000원' },
      { emoji: '🥘', title: '찌개/탕', description: '된장찌개, 김치찌개', price: '9,000원' },
      { emoji: '🍖', title: '고기', description: '불고기, 갈비찜', price: '15,000원~' },
      { emoji: '🍲', title: '전골', description: '부대찌개, 버섯전골', price: '25,000원~' },
    ],
    keywords: ['한식', '식당', '밥집', '가정식'],
  },
  {
    id: 'restaurant-bbq',
    name: '고깃집/BBQ',
    nameEn: 'BBQ Restaurant',
    category: 'food',
    description: '고기집/BBQ 소개 페이지',
    icon: '🥩',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=1920',
      overlayOpacity: 50,
      title: '육즙 가득\n프리미엄 고기',
      subtitle: '신선한 1++ 한우, 숙성 삼겹살',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '육회관', tagline: '프리미엄 한우 전문점' },
    defaultServices: [
      { emoji: '🥩', title: '한우', description: '등심, 채끝, 안심', price: '100g 25,000원~' },
      { emoji: '🐷', title: '삼겹살', description: '숙성 삼겹, 목살', price: '200g 18,000원' },
      { emoji: '🍖', title: '갈비', description: 'LA갈비, 생갈비', price: '200g 22,000원' },
      { emoji: '🥗', title: '사이드', description: '냉면, 된장찌개', price: '9,000원' },
    ],
    keywords: ['고깃집', 'BBQ', '삼겹살', '한우'],
  },
  {
    id: 'bakery',
    name: '베이커리',
    nameEn: 'Bakery',
    category: 'food',
    description: '베이커리/빵집 소개 페이지',
    icon: '🥐',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1920',
      overlayOpacity: 40,
      title: '갓 구운 빵의\n행복',
      subtitle: '매일 아침 직접 구운 신선한 빵',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '밀가루 연구소', tagline: '천연발효빵 전문점' },
    defaultServices: [
      { emoji: '🥖', title: '식빵', description: '우유식빵, 통밀식빵', price: '5,000원~' },
      { emoji: '🥐', title: '페이스트리', description: '크루아상, 소금빵', price: '3,500원~' },
      { emoji: '🍰', title: '케이크', description: '생크림, 티라미수', price: '35,000원~' },
      { emoji: '🍩', title: '도넛', description: '글레이즈, 생크림', price: '3,000원~' },
    ],
    keywords: ['베이커리', '빵집', '제과점', '케이크'],
  },
  {
    id: 'sushi',
    name: '초밥집/일식',
    nameEn: 'Sushi Restaurant',
    category: 'food',
    description: '초밥/일식집 소개 페이지',
    icon: '🍣',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1920',
      overlayOpacity: 50,
      title: '신선한 재료\n장인의 손맛',
      subtitle: '오마카세, 모둠초밥 전문',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '스시 오마카세', tagline: '제철 스시 전문점' },
    defaultServices: [
      { emoji: '🍣', title: '오마카세', description: '셰프 추천 코스', price: '80,000원~' },
      { emoji: '🍱', title: '모둠초밥', description: '12~18피스', price: '35,000원~' },
      { emoji: '🍜', title: '라멘', description: '돈코츠, 미소', price: '12,000원' },
      { emoji: '🍶', title: '사케', description: '다이긴죠, 준마이', price: '15,000원~' },
    ],
    keywords: ['초밥', '스시', '일식', '오마카세'],
  },
  {
    id: 'pizza',
    name: '피자집',
    nameEn: 'Pizzeria',
    category: 'food',
    description: '피자 전문점 소개 페이지',
    icon: '🍕',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1920',
      overlayOpacity: 50,
      title: '화덕에서\n갓 구운 피자',
      subtitle: '이탈리안 정통 나폴리 피자',
      primaryCTA: { label: '주문하기', href: '#menu' },
    },
    defaultBusiness: { name: '피자올로', tagline: '나폴리 화덕피자 전문점' },
    defaultServices: [
      { emoji: '🍕', title: '마르게리타', description: '토마토, 모짜렐라, 바질', price: '18,000원' },
      { emoji: '🧀', title: '콰트로포르마지', description: '4가지 치즈', price: '22,000원' },
      { emoji: '🥓', title: '디아볼라', description: '살라미, 칠리', price: '20,000원' },
      { emoji: '🍝', title: '파스타', description: '까르보나라, 봉골레', price: '16,000원' },
    ],
    keywords: ['피자', '이탈리안', '화덕피자', '파스타'],
  },

  // ==================== 건강/운동 (10개) ====================
  {
    id: 'gym',
    name: '헬스장/피트니스',
    nameEn: 'Fitness Gym',
    category: 'health',
    description: '헬스장/피트니스 센터 소개 페이지',
    icon: '💪',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1920',
      overlayOpacity: 50,
      title: '당신의 한계를\n넘어서',
      subtitle: '최신 장비, 전문 트레이너',
      primaryCTA: { label: '무료 체험', href: '#contact' },
    },
    defaultBusiness: { name: '파워짐', tagline: '24시 피트니스 센터' },
    defaultServices: [
      { emoji: '🏋️', title: '헬스', description: '웨이트, 유산소', price: '월 89,000원' },
      { emoji: '👤', title: 'PT', description: '1:1 개인 트레이닝', price: '회 70,000원' },
      { emoji: '👥', title: 'GX', description: '그룹 운동 수업', price: '월 59,000원' },
      { emoji: '🧘', title: '요가/필라테스', description: '스튜디오 수업', price: '월 99,000원' },
    ],
    keywords: ['헬스', '피트니스', '헬스장', 'PT'],
  },
  {
    id: 'yoga-pilates',
    name: '요가/필라테스',
    nameEn: 'Yoga & Pilates',
    category: 'health',
    description: '요가/필라테스 스튜디오 소개 페이지',
    icon: '🧘',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1920',
      overlayOpacity: 40,
      title: '몸과 마음의\n균형을 찾아서',
      subtitle: '소수정예 프리미엄 수업',
      primaryCTA: { label: '체험 신청', href: '#contact' },
    },
    defaultBusiness: { name: '밸런스 요가', tagline: '빈야사, 핫요가 전문' },
    defaultServices: [
      { emoji: '🧘‍♀️', title: '요가', description: '빈야사, 아쉬탕가', price: '월 150,000원' },
      { emoji: '💪', title: '필라테스', description: '기구, 매트 필라테스', price: '월 180,000원' },
      { emoji: '🔥', title: '핫요가', description: '38도 핫요가', price: '월 130,000원' },
      { emoji: '👤', title: '1:1 수업', description: '개인 맞춤 수업', price: '회 80,000원' },
    ],
    keywords: ['요가', '필라테스', '명상', '스트레칭'],
  },
  {
    id: 'swimming-pool',
    name: '수영장',
    nameEn: 'Swimming Pool',
    category: 'health',
    description: '수영장/아쿠아센터 소개 페이지',
    icon: '🏊',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?w=1920',
      overlayOpacity: 50,
      title: '맑은 물에서\n건강을 지키세요',
      subtitle: '성인, 어린이 수영 레슨',
      primaryCTA: { label: '등록 문의', href: '#contact' },
    },
    defaultBusiness: { name: '블루워터 수영장', tagline: '25m 정규 수영장' },
    defaultServices: [
      { emoji: '🏊', title: '성인 수영', description: '초급~고급반', price: '월 100,000원' },
      { emoji: '👶', title: '어린이 수영', description: '5세 이상', price: '월 80,000원' },
      { emoji: '💧', title: '아쿠아로빅', description: '수중 운동', price: '월 90,000원' },
      { emoji: '🎽', title: '자유수영', description: '시간권', price: '1회 8,000원' },
    ],
    keywords: ['수영', '수영장', '아쿠아', '레슨'],
  },
  {
    id: 'crossfit',
    name: '크로스핏',
    nameEn: 'CrossFit',
    category: 'health',
    description: '크로스핏 박스 소개 페이지',
    icon: '🏋️',
    defaultHero: {
      type: 'video',
      backgroundUrl: '/videos/crossfit.mp4',
      overlayOpacity: 60,
      title: '더 강하게\n더 빠르게',
      subtitle: '함께 땀 흘리며 성장하는 커뮤니티',
      primaryCTA: { label: '무료 체험', href: '#contact' },
    },
    defaultBusiness: { name: '크로스핏 강남', tagline: 'CrossFit Affiliate Box' },
    defaultServices: [
      { emoji: '🏋️', title: 'WOD', description: '매일 다른 고강도 운동', price: '월 180,000원' },
      { emoji: '💪', title: '역도', description: '스내치, 클린앤저크', price: '월 200,000원' },
      { emoji: '👥', title: '팀워드', description: '파트너 운동', price: '포함' },
      { emoji: '🏃', title: '컨디셔닝', description: '유산소 강화', price: '포함' },
    ],
    keywords: ['크로스핏', '고강도', '역도', '운동'],
  },

  // ==================== 이벤트 (8개) ====================
  {
    id: 'wedding-planner',
    name: '웨딩플래너',
    nameEn: 'Wedding Planner',
    category: 'event',
    description: '웨딩 플래너 소개 페이지',
    icon: '💒',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1920',
      overlayOpacity: 40,
      title: '인생 최고의 순간을\n완벽하게',
      subtitle: '맞춤형 웨딩 토탈 케어',
      primaryCTA: { label: '상담 예약', href: '#contact' },
    },
    defaultBusiness: { name: '블리스 웨딩', tagline: '프리미엄 웨딩 컨설팅' },
    defaultServices: [
      { emoji: '💒', title: '웨딩홀', description: '예식장 투어, 예약 대행' },
      { emoji: '💐', title: '스드메', description: '스튜디오, 드레스, 메이크업' },
      { emoji: '🎊', title: '본식', description: '사회자, 연주, 촬영' },
      { emoji: '✈️', title: '신혼여행', description: '허니문 플래닝' },
    ],
    keywords: ['웨딩', '결혼', '플래너', '웨딩홀'],
  },
  {
    id: 'photo-studio',
    name: '사진관/스튜디오',
    nameEn: 'Photo Studio',
    category: 'event',
    description: '사진 스튜디오 소개 페이지',
    icon: '📸',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1471341971476-ae15ff5dd4ea?w=1920',
      overlayOpacity: 50,
      title: '당신의 소중한 순간을\n담습니다',
      subtitle: '프로필, 가족사진, 웨딩 촬영',
      primaryCTA: { label: '촬영 예약', href: '#contact' },
    },
    defaultBusiness: { name: '모먼트 스튜디오', tagline: '프로필, 웨딩 전문' },
    defaultServices: [
      { emoji: '📸', title: '프로필', description: '증명사진, 비즈니스 프로필', price: '50,000원~' },
      { emoji: '👨‍👩‍👧', title: '가족사진', description: '가족, 돌잔치', price: '200,000원~' },
      { emoji: '💒', title: '웨딩', description: '스튜디오, 야외 촬영', price: '500,000원~' },
      { emoji: '🎓', title: '졸업사진', description: '학위복, 한복', price: '100,000원~' },
    ],
    keywords: ['사진관', '스튜디오', '프로필', '촬영'],
  },
  {
    id: 'party-venue',
    name: '파티룸/이벤트홀',
    nameEn: 'Party Venue',
    category: 'event',
    description: '파티룸/이벤트 공간 소개 페이지',
    icon: '🎉',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1920',
      overlayOpacity: 50,
      title: '특별한 파티\n완벽한 공간',
      subtitle: '생일, 브라이덜샤워, 기업행사',
      primaryCTA: { label: '예약 문의', href: '#contact' },
    },
    defaultBusiness: { name: '파티하우스', tagline: '프라이빗 파티룸' },
    defaultServices: [
      { emoji: '🎂', title: '생일파티', description: '케이크, 풍선 장식', price: '시간당 50,000원~' },
      { emoji: '💍', title: '브라이덜샤워', description: '소품, 포토존', price: '시간당 70,000원~' },
      { emoji: '🎊', title: '기업행사', description: '워크샵, 송년회', price: '견적 문의' },
      { emoji: '👶', title: '돌잔치', description: '전통 상차림, 포토월', price: '견적 문의' },
    ],
    keywords: ['파티룸', '이벤트', '파티', '대관'],
  },

  // ==================== 서비스업 (10개) ====================
  {
    id: 'car-wash',
    name: '세차/광택',
    nameEn: 'Car Wash',
    category: 'service',
    description: '세차/디테일링 샵 소개 페이지',
    icon: '🚗',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=1920',
      overlayOpacity: 50,
      title: '새 차처럼\n빛나게',
      subtitle: '프리미엄 손세차, 디테일링',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '카샤인', tagline: '프리미엄 손세차 전문' },
    defaultServices: [
      { emoji: '🧽', title: '외부세차', description: '손세차, 왁스', price: '35,000원~' },
      { emoji: '🧹', title: '내부세차', description: '실내 클리닝', price: '50,000원~' },
      { emoji: '✨', title: '광택', description: '연마, 코팅', price: '200,000원~' },
      { emoji: '🛡️', title: '유리막코팅', description: '세라믹 코팅', price: '500,000원~' },
    ],
    keywords: ['세차', '손세차', '광택', '디테일링'],
  },
  {
    id: 'moving-service',
    name: '이사/용달',
    nameEn: 'Moving Service',
    category: 'service',
    description: '이사/용달 서비스 소개 페이지',
    icon: '🚚',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '안전하고\n빠른 이사',
      subtitle: '포장이사부터 원룸이사까지',
      primaryCTA: { label: '무료 견적', href: '#contact' },
    },
    defaultBusiness: { name: '든든이사', tagline: '포장이사 전문' },
    defaultServices: [
      { emoji: '📦', title: '포장이사', description: '전체 포장, 정리정돈', price: '견적 문의' },
      { emoji: '🏠', title: '일반이사', description: '가구, 짐 운반', price: '견적 문의' },
      { emoji: '🚐', title: '원룸이사', description: '소형 이사', price: '200,000원~' },
      { emoji: '🏢', title: '사무실이사', description: '기업 이전', price: '견적 문의' },
    ],
    keywords: ['이사', '포장이사', '용달', '이삿짐'],
  },
  {
    id: 'cleaning-service',
    name: '청소/가사도우미',
    nameEn: 'Cleaning Service',
    category: 'service',
    description: '청소/가사 서비스 소개 페이지',
    icon: '🧹',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '깨끗한 집에서\n편안한 휴식',
      subtitle: '입주청소, 정기청소, 가사도우미',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '맑은청소', tagline: '전문 청소 서비스' },
    defaultServices: [
      { emoji: '🏠', title: '입주청소', description: '이사 전후 대청소', price: '평당 35,000원' },
      { emoji: '🔄', title: '정기청소', description: '주1회/월2회', price: '시간당 25,000원' },
      { emoji: '👩‍👧', title: '가사도우미', description: '요리, 빨래, 청소', price: '시간당 18,000원' },
      { emoji: '🏢', title: '사무실청소', description: '사무공간 관리', price: '견적 문의' },
    ],
    keywords: ['청소', '입주청소', '가사도우미', '가정부'],
  },
  {
    id: 'repair-handyman',
    name: '수리/핸디맨',
    nameEn: 'Handyman Service',
    category: 'service',
    description: '집수리/핸디맨 서비스 소개 페이지',
    icon: '🔧',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '집안 문제\n한 번에 해결',
      subtitle: '수도, 전기, 가구 조립 등',
      primaryCTA: { label: '출장 요청', href: '#contact' },
    },
    defaultBusiness: { name: '만능 수리왕', tagline: '24시간 출장 서비스' },
    defaultServices: [
      { emoji: '🚰', title: '수도/배관', description: '수전, 누수, 막힘', price: '출장비 30,000원~' },
      { emoji: '💡', title: '전기', description: '조명, 콘센트, 스위치', price: '출장비 30,000원~' },
      { emoji: '🪑', title: '가구조립', description: '조립, 이동, 철거', price: '건당 20,000원~' },
      { emoji: '🚪', title: '도어/잠금', description: '잠금장치, 경첩', price: '출장비 30,000원~' },
    ],
    keywords: ['수리', '핸디맨', '출장수리', '집수리'],
  },
  {
    id: 'laundry',
    name: '세탁소',
    nameEn: 'Laundry',
    category: 'service',
    description: '세탁소/드라이클리닝 소개 페이지',
    icon: '👔',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '새 옷처럼\n깨끗하게',
      subtitle: '프리미엄 드라이클리닝',
      primaryCTA: { label: '수거 신청', href: '#contact' },
    },
    defaultBusiness: { name: '크린토피아', tagline: '품질 보증 세탁' },
    defaultServices: [
      { emoji: '👔', title: '일반세탁', description: '와이셔츠, 정장', price: '2,000원~' },
      { emoji: '🧥', title: '드라이클리닝', description: '코트, 니트, 스웨터', price: '10,000원~' },
      { emoji: '🛏️', title: '이불세탁', description: '이불, 베개, 커튼', price: '15,000원~' },
      { emoji: '👟', title: '신발세탁', description: '운동화, 구두', price: '8,000원~' },
    ],
    keywords: ['세탁소', '드라이클리닝', '세탁', '빨래'],
  },

  // ==================== 소매/리테일 (8개) ====================
  {
    id: 'flower-shop',
    name: '꽃집/플라워샵',
    nameEn: 'Flower Shop',
    category: 'retail',
    description: '플라워샵 소개 페이지',
    icon: '💐',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=1920',
      overlayOpacity: 40,
      title: '감동을 전하는\n꽃다발',
      subtitle: '기념일, 축하, 조화 전문',
      primaryCTA: { label: '주문하기', href: '#contact' },
    },
    defaultBusiness: { name: '블루밍', tagline: '프리미엄 플라워샵' },
    defaultServices: [
      { emoji: '💐', title: '꽃다발', description: '생화 꽃다발', price: '50,000원~' },
      { emoji: '🌸', title: '꽃바구니', description: '축하, 문병', price: '70,000원~' },
      { emoji: '🎀', title: '화환', description: '축하, 근조', price: '80,000원~' },
      { emoji: '🌹', title: '정기배송', description: '주/월 정기 꽃', price: '월 100,000원~' },
    ],
    keywords: ['꽃집', '플라워', '꽃다발', '화환'],
  },
  {
    id: 'clothing-store',
    name: '의류매장',
    nameEn: 'Clothing Store',
    category: 'retail',
    description: '의류/패션 매장 소개 페이지',
    icon: '👗',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1920',
      overlayOpacity: 50,
      title: '당신의 스타일을\n완성합니다',
      subtitle: '트렌디한 패션 셀렉트샵',
      primaryCTA: { label: '새 컬렉션 보기', href: '#products' },
    },
    defaultBusiness: { name: '스타일 라운지', tagline: '여성 패션 셀렉트샵' },
    defaultServices: [
      { emoji: '👗', title: '원피스', description: '데일리, 오피스룩' },
      { emoji: '👖', title: '팬츠', description: '데님, 슬랙스' },
      { emoji: '🧥', title: '아우터', description: '재킷, 코트' },
      { emoji: '👜', title: '악세서리', description: '가방, 주얼리' },
    ],
    keywords: ['의류', '패션', '옷가게', '셀렉트샵'],
  },

  // ==================== 반려동물 (5개) ====================
  {
    id: 'pet-shop',
    name: '펫샵',
    nameEn: 'Pet Shop',
    category: 'pet',
    description: '펫샵/반려동물용품점 소개 페이지',
    icon: '🐾',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1920',
      overlayOpacity: 50,
      title: '반려동물을 위한\n모든 것',
      subtitle: '사료, 용품, 간식 전문',
      primaryCTA: { label: '상품 보기', href: '#products' },
    },
    defaultBusiness: { name: '펫파라다이스', tagline: '프리미엄 펫용품 전문점' },
    defaultServices: [
      { emoji: '🦴', title: '사료', description: '수입/국산 프리미엄' },
      { emoji: '🧸', title: '장난감', description: '안전한 펫토이' },
      { emoji: '🛏️', title: '하우스', description: '침대, 캔넬' },
      { emoji: '🧴', title: '케어용품', description: '샴푸, 브러시' },
    ],
    keywords: ['펫샵', '반려동물', '펫용품', '사료'],
  },
  {
    id: 'pet-grooming',
    name: '펫미용',
    nameEn: 'Pet Grooming',
    category: 'pet',
    description: '반려동물 미용샵 소개 페이지',
    icon: '✂️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=1920',
      overlayOpacity: 50,
      title: '우리 아이\n더 예쁘게',
      subtitle: '전문 반려동물 미용 서비스',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '펫살롱', tagline: '강아지 미용 전문' },
    defaultServices: [
      { emoji: '🛁', title: '목욕', description: '샴푸, 드라이', price: '소형 30,000원~' },
      { emoji: '✂️', title: '전체미용', description: '컷, 스타일링', price: '소형 50,000원~' },
      { emoji: '🐾', title: '부분미용', description: '발바닥, 얼굴', price: '15,000원~' },
      { emoji: '🦷', title: '스케일링', description: '치석 제거', price: '50,000원~' },
    ],
    keywords: ['펫미용', '강아지미용', '반려동물', '그루밍'],
  },

  // ==================== 여행/숙박 (5개) ====================
  {
    id: 'guesthouse',
    name: '게스트하우스/민박',
    nameEn: 'Guesthouse',
    category: 'travel',
    description: '게스트하우스/민박 소개 페이지',
    icon: '🏡',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1920',
      overlayOpacity: 40,
      title: '편안한 휴식\n특별한 여행',
      subtitle: '아늑한 숙소에서의 하룻밤',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '여행자의 집', tagline: '가정적인 분위기의 게스트하우스' },
    defaultServices: [
      { emoji: '🛏️', title: '도미토리', description: '4인실', price: '박 30,000원' },
      { emoji: '🏠', title: '개인실', description: '2인실', price: '박 60,000원' },
      { emoji: '👨‍👩‍👧', title: '가족실', description: '4인 가족', price: '박 100,000원' },
      { emoji: '🍳', title: '조식', description: '아침식사', price: '8,000원' },
    ],
    keywords: ['게스트하우스', '민박', '숙소', '펜션'],
  },
  {
    id: 'pension',
    name: '펜션',
    nameEn: 'Pension',
    category: 'travel',
    description: '펜션 소개 페이지',
    icon: '🏔️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1920',
      overlayOpacity: 40,
      title: '자연 속\n힐링 펜션',
      subtitle: '스파, 바베큐, 오션뷰',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '숲속펜션', tagline: '프라이빗 풀빌라' },
    defaultServices: [
      { emoji: '🏊', title: '풀빌라', description: '개인 수영장', price: '박 300,000원~' },
      { emoji: '🌲', title: '숲속방', description: '산림욕', price: '박 150,000원~' },
      { emoji: '🌊', title: '오션뷰', description: '바다 전망', price: '박 200,000원~' },
      { emoji: '🔥', title: '바베큐', description: 'BBQ 세트', price: '추가 50,000원' },
    ],
    keywords: ['펜션', '풀빌라', '숙박', '휴양'],
  },

  // ==================== 개인/포트폴리오 (5개) ====================
  {
    id: 'personal-portfolio',
    name: '개인 포트폴리오',
    nameEn: 'Personal Portfolio',
    category: 'personal',
    description: '개인 포트폴리오 소개 페이지',
    icon: '👤',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '안녕하세요\n저는 개발자입니다',
      subtitle: '웹 프론트엔드 개발자 홍길동입니다',
      primaryCTA: { label: '프로젝트 보기', href: '#projects' },
      secondaryCTA: { label: '연락하기', href: '#contact' },
    },
    defaultBusiness: { name: '홍길동', tagline: 'Frontend Developer' },
    defaultServices: [
      { emoji: '💻', title: '웹 개발', description: 'React, Next.js, Vue' },
      { emoji: '📱', title: '앱 개발', description: 'React Native, Flutter' },
      { emoji: '🎨', title: 'UI/UX', description: 'Figma, Adobe XD' },
      { emoji: '🔧', title: '기타', description: 'Node.js, Python' },
    ],
    keywords: ['포트폴리오', '개발자', '프리랜서', '이력서'],
  },
  {
    id: 'freelancer',
    name: '프리랜서',
    nameEn: 'Freelancer',
    category: 'personal',
    description: '프리랜서 소개 페이지',
    icon: '💼',
    defaultHero: {
      type: 'gradient',
      overlayOpacity: 30,
      title: '당신의 프로젝트를\n함께 완성합니다',
      subtitle: '10년 경력 시니어 프리랜서',
      primaryCTA: { label: '프로젝트 문의', href: '#contact' },
    },
    defaultBusiness: { name: '프리랜서 김', tagline: '웹/앱 개발 전문' },
    defaultServices: [
      { emoji: '🌐', title: '웹사이트', description: '반응형 웹 제작' },
      { emoji: '🛒', title: '쇼핑몰', description: '이커머스 구축' },
      { emoji: '📱', title: '앱 개발', description: 'iOS/Android' },
      { emoji: '🔧', title: '유지보수', description: '기존 시스템 개선' },
    ],
    keywords: ['프리랜서', '외주', '개발', '디자인'],
  },

  // ==================== 추가 전문직 (10개) ====================
  {
    id: 'dermatology',
    name: '피부과',
    nameEn: 'Dermatology',
    category: 'professional',
    description: '피부과/성형외과 소개 페이지',
    icon: '💎',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1920',
      overlayOpacity: 50,
      title: '피부가 답을\n말해줍니다',
      subtitle: '레이저, 보톡스, 필러 전문',
      primaryCTA: { label: '상담 예약', href: '#contact' },
    },
    defaultBusiness: { name: '클리어 피부과', tagline: '미용/피부질환 전문' },
    defaultServices: [
      { emoji: '✨', title: '레이저', description: '기미, 색소, 흉터' },
      { emoji: '💉', title: '보톡스/필러', description: '주름, 볼륨' },
      { emoji: '💫', title: '리프팅', description: '울쎄라, 써마지' },
      { emoji: '🌿', title: '피부질환', description: '여드름, 아토피' },
    ],
    keywords: ['피부과', '성형', '보톡스', '레이저'],
  },
  {
    id: 'orthopedic',
    name: '정형외과',
    nameEn: 'Orthopedics',
    category: 'professional',
    description: '정형외과 소개 페이지',
    icon: '🦴',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1920',
      overlayOpacity: 50,
      title: '통증 없는 삶을\n되찾으세요',
      subtitle: '관절, 척추, 스포츠의학 전문',
      primaryCTA: { label: '진료 예약', href: '#contact' },
    },
    defaultBusiness: { name: '건강 정형외과', tagline: '척추/관절 비수술 치료' },
    defaultServices: [
      { emoji: '🦴', title: '척추', description: '디스크, 협착증' },
      { emoji: '🦵', title: '관절', description: '무릎, 어깨, 고관절' },
      { emoji: '⚽', title: '스포츠의학', description: '부상 치료, 재활' },
      { emoji: '💪', title: '재활치료', description: '도수치료, 운동치료' },
    ],
    keywords: ['정형외과', '척추', '관절', '통증'],
  },
  {
    id: 'ophthalmology',
    name: '안과',
    nameEn: 'Ophthalmology',
    category: 'professional',
    description: '안과 소개 페이지',
    icon: '👁️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1920',
      overlayOpacity: 50,
      title: '맑은 눈으로\n세상을 보세요',
      subtitle: '라식, 라섹, 백내장 전문',
      primaryCTA: { label: '검진 예약', href: '#contact' },
    },
    defaultBusiness: { name: '비전 안과', tagline: '시력교정 전문' },
    defaultServices: [
      { emoji: '👁️', title: '라식/라섹', description: '시력교정술' },
      { emoji: '🔬', title: '백내장', description: '다초점렌즈 삽입' },
      { emoji: '👓', title: '노안교정', description: '돋보기 불필요' },
      { emoji: '🩺', title: '종합검진', description: '녹내장, 망막' },
    ],
    keywords: ['안과', '라식', '백내장', '시력'],
  },
  {
    id: 'obgyn',
    name: '산부인과',
    nameEn: 'OBGYN',
    category: 'professional',
    description: '산부인과 소개 페이지',
    icon: '👶',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=1920',
      overlayOpacity: 50,
      title: '여성의 건강을\n지켜드립니다',
      subtitle: '임신, 출산, 여성질환 전문',
      primaryCTA: { label: '상담 예약', href: '#contact' },
    },
    defaultBusiness: { name: '맘스 산부인과', tagline: '산전관리, 여성건강 전문' },
    defaultServices: [
      { emoji: '🤰', title: '임신/출산', description: '산전관리, 분만' },
      { emoji: '👶', title: '태아초음파', description: '4D 정밀초음파' },
      { emoji: '💊', title: '여성질환', description: '생리불순, 갱년기' },
      { emoji: '🔬', title: '검진', description: '자궁경부암, 유방' },
    ],
    keywords: ['산부인과', '산전관리', '여성건강', '임신'],
  },
  {
    id: 'pediatrics',
    name: '소아과',
    nameEn: 'Pediatrics',
    category: 'professional',
    description: '소아청소년과 소개 페이지',
    icon: '🧒',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=1920',
      overlayOpacity: 50,
      title: '아이들의 건강한\n성장을 함께합니다',
      subtitle: '영유아, 청소년 진료 전문',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '아이사랑 소아과', tagline: '성장발달, 예방접종 전문' },
    defaultServices: [
      { emoji: '🧒', title: '일반진료', description: '감기, 장염, 피부' },
      { emoji: '💉', title: '예방접종', description: '국가필수, 선택접종' },
      { emoji: '📏', title: '성장검진', description: '발달검사, 성장호르몬' },
      { emoji: '🤧', title: '알레르기', description: '비염, 천식, 아토피' },
    ],
    keywords: ['소아과', '소아청소년과', '예방접종', '아기'],
  },
  {
    id: 'labor-attorney',
    name: '노무사',
    nameEn: 'Labor Attorney',
    category: 'professional',
    description: '노무사/인사노무 소개 페이지',
    icon: '📋',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '노동의 가치를\n지켜드립니다',
      subtitle: '인사노무, 노동법 전문',
      primaryCTA: { label: '무료 상담', href: '#contact' },
    },
    defaultBusiness: { name: '정의 노무법인', tagline: '기업인사, 노동법 전문' },
    defaultServices: [
      { emoji: '📋', title: '인사관리', description: '채용, 급여, 취업규칙' },
      { emoji: '⚖️', title: '노동법', description: '부당해고, 임금체불' },
      { emoji: '🏢', title: '기업자문', description: '4대보험, 근로계약' },
      { emoji: '🤝', title: '노사협상', description: '단체협약, 분쟁조정' },
    ],
    keywords: ['노무사', '인사', '노동법', '급여'],
  },
  {
    id: 'insurance-agent',
    name: '보험설계사/GA',
    nameEn: 'Insurance Agent',
    category: 'professional',
    description: '보험설계사 소개 페이지',
    icon: '🛡️',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '미래의 안전을\n설계합니다',
      subtitle: '생명보험, 손해보험 전문',
      primaryCTA: { label: '무료 진단', href: '#contact' },
    },
    defaultBusiness: { name: '안심 보험설계', tagline: '맞춤형 보험 컨설팅' },
    defaultServices: [
      { emoji: '💚', title: '생명보험', description: '종신, 연금, 저축' },
      { emoji: '🚗', title: '손해보험', description: '자동차, 화재, 상해' },
      { emoji: '🏥', title: '실비보험', description: '의료비 보장' },
      { emoji: '📊', title: '보험리모델링', description: '보험료 절감' },
    ],
    keywords: ['보험', '보험설계', 'GA', '생명보험'],
  },
  {
    id: 'financial-planner',
    name: '재무설계사/IFA',
    nameEn: 'Financial Planner',
    category: 'professional',
    description: '재무설계사 소개 페이지',
    icon: '💰',
    defaultHero: {
      type: 'gradient',
      overlayOpacity: 30,
      title: '돈이 일하게\n만들어드립니다',
      subtitle: '자산관리, 투자상담 전문',
      primaryCTA: { label: '무료 상담', href: '#contact' },
    },
    defaultBusiness: { name: '웰스 재무설계', tagline: '자산관리 전문' },
    defaultServices: [
      { emoji: '💰', title: '자산관리', description: '포트폴리오 구성' },
      { emoji: '🏠', title: '부동산', description: '투자, 절세 전략' },
      { emoji: '👴', title: '은퇴설계', description: '연금, 노후준비' },
      { emoji: '📈', title: '투자상담', description: '주식, 펀드, ETF' },
    ],
    keywords: ['재무설계', '자산관리', '투자', 'IFA'],
  },
  {
    id: 'notary',
    name: '법무사',
    nameEn: 'Notary',
    category: 'professional',
    description: '법무사 사무소 소개 페이지',
    icon: '📜',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '복잡한 법률 절차\n깔끔하게',
      subtitle: '등기, 소송서류 전문',
      primaryCTA: { label: '상담 신청', href: '#contact' },
    },
    defaultBusiness: { name: '신뢰 법무사', tagline: '부동산등기 전문' },
    defaultServices: [
      { emoji: '🏠', title: '부동산등기', description: '매매, 상속, 증여' },
      { emoji: '🏢', title: '법인등기', description: '설립, 변경, 이전' },
      { emoji: '📝', title: '소송서류', description: '지급명령, 소장' },
      { emoji: '📋', title: '기타', description: '공정증서, 인증' },
    ],
    keywords: ['법무사', '등기', '부동산', '법인'],
  },
  {
    id: 'appraisal',
    name: '감정평가사',
    nameEn: 'Appraiser',
    category: 'professional',
    description: '감정평가사 소개 페이지',
    icon: '🏘️',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '정확한 가치\n객관적인 평가',
      subtitle: '부동산/동산 감정평가 전문',
      primaryCTA: { label: '평가 의뢰', href: '#contact' },
    },
    defaultBusiness: { name: '정밀 감정평가법인', tagline: '부동산 감정 전문' },
    defaultServices: [
      { emoji: '🏠', title: '부동산', description: '토지, 건물, 아파트' },
      { emoji: '🏭', title: '기업자산', description: '기계, 설비, 영업권' },
      { emoji: '📊', title: '보상평가', description: '수용, 보상 감정' },
      { emoji: '⚖️', title: '소송감정', description: '재판 목적 감정' },
    ],
    keywords: ['감정평가', '부동산', '자산평가', '감정'],
  },

  // ==================== 추가 교육 (7개) ====================
  {
    id: 'tutoring',
    name: '과외/개인지도',
    nameEn: 'Private Tutoring',
    category: 'education',
    description: '과외 선생님 소개 페이지',
    icon: '📖',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '1:1 맞춤 수업으로\n성적 UP',
      subtitle: 'SKY 출신 전문 과외',
      primaryCTA: { label: '상담 신청', href: '#contact' },
    },
    defaultBusiness: { name: '탑클래스 과외', tagline: '수학/영어 전문' },
    defaultServices: [
      { emoji: '🔢', title: '수학', description: '초중고 전 과정' },
      { emoji: '🇺🇸', title: '영어', description: '내신/수능 완벽 대비' },
      { emoji: '🔬', title: '과학', description: '물리/화학/생물' },
      { emoji: '📚', title: '국어', description: '문학/비문학/논술' },
    ],
    keywords: ['과외', '개인지도', '1:1', '내신'],
  },
  {
    id: 'entrance-exam',
    name: '입시학원',
    nameEn: 'Entrance Exam Academy',
    category: 'education',
    description: '입시학원 소개 페이지',
    icon: '🎓',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1920',
      overlayOpacity: 50,
      title: '목표 대학\n반드시 합격',
      subtitle: '수능/내신/논술 전문',
      primaryCTA: { label: '입학 상담', href: '#contact' },
    },
    defaultBusiness: { name: '합격 입시학원', tagline: '대입 전문 학원' },
    defaultServices: [
      { emoji: '📝', title: '수능', description: '수능 집중반' },
      { emoji: '📊', title: '내신', description: '내신 완벽 대비' },
      { emoji: '✍️', title: '논술', description: '대학별 논술반' },
      { emoji: '🗣️', title: '면접', description: '면접 특강' },
    ],
    keywords: ['입시', '수능', '논술', '대입'],
  },
  {
    id: 'kindergarten',
    name: '유치원/어린이집',
    nameEn: 'Kindergarten',
    category: 'education',
    description: '유치원/어린이집 소개 페이지',
    icon: '🌈',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=1920',
      overlayOpacity: 40,
      title: '사랑으로 키우는\n우리 아이',
      subtitle: '안전하고 즐거운 배움터',
      primaryCTA: { label: '입학 문의', href: '#contact' },
    },
    defaultBusiness: { name: '햇살 유치원', tagline: '자연친화 교육' },
    defaultServices: [
      { emoji: '🎨', title: '창의교육', description: '미술, 음악, 체육' },
      { emoji: '🌍', title: '영어교육', description: '원어민 수업' },
      { emoji: '🌿', title: '자연학습', description: '텃밭, 숲체험' },
      { emoji: '🚌', title: '통학버스', description: '안전한 등하원' },
    ],
    keywords: ['유치원', '어린이집', '유아교육', '어린이'],
  },
  {
    id: 'study-abroad',
    name: '유학원',
    nameEn: 'Study Abroad Agency',
    category: 'education',
    description: '유학원 소개 페이지',
    icon: '✈️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1920',
      overlayOpacity: 50,
      title: '세계로 나가는\n첫걸음',
      subtitle: '미국/영국/캐나다/호주 유학 전문',
      primaryCTA: { label: '무료 상담', href: '#contact' },
    },
    defaultBusiness: { name: '글로벌 유학원', tagline: '해외 유학/연수 전문' },
    defaultServices: [
      { emoji: '🎓', title: '정규유학', description: '대학, 대학원' },
      { emoji: '📚', title: '어학연수', description: '단기/장기 연수' },
      { emoji: '🏫', title: '조기유학', description: '중고등학교' },
      { emoji: '💼', title: '비자', description: '학생비자 대행' },
    ],
    keywords: ['유학', '유학원', '어학연수', '해외'],
  },
  {
    id: 'dance-studio',
    name: '댄스학원',
    nameEn: 'Dance Studio',
    category: 'education',
    description: '댄스/발레 학원 소개 페이지',
    icon: '💃',
    defaultHero: {
      type: 'video',
      backgroundUrl: '/videos/dance.mp4',
      overlayOpacity: 50,
      title: '춤으로 표현하는\n나만의 스타일',
      subtitle: '케이팝, 힙합, 발레 전문',
      primaryCTA: { label: '체험 신청', href: '#contact' },
    },
    defaultBusiness: { name: '무브 댄스 스튜디오', tagline: '케이팝 댄스 전문' },
    defaultServices: [
      { emoji: '💃', title: 'K-POP', description: '아이돌 안무 커버' },
      { emoji: '🕺', title: '힙합', description: '스트릿 댄스' },
      { emoji: '🩰', title: '발레', description: '클래식 발레' },
      { emoji: '🎵', title: '방송댄스', description: '오디션 준비' },
    ],
    keywords: ['댄스', '춤', '케이팝', '힙합'],
  },
  {
    id: 'cooking-class',
    name: '요리학원',
    nameEn: 'Cooking Class',
    category: 'education',
    description: '요리학원/쿠킹클래스 소개 페이지',
    icon: '👨‍🍳',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1920',
      overlayOpacity: 50,
      title: '요리의 즐거움을\n발견하세요',
      subtitle: '한식, 양식, 베이킹 전문',
      primaryCTA: { label: '수업 신청', href: '#contact' },
    },
    defaultBusiness: { name: '쉐프의 주방', tagline: '원데이 클래스 전문' },
    defaultServices: [
      { emoji: '🍳', title: '한식', description: '가정식, 반찬' },
      { emoji: '🍝', title: '양식', description: '파스타, 스테이크' },
      { emoji: '🍰', title: '베이킹', description: '케이크, 쿠키' },
      { emoji: '🍣', title: '일식', description: '초밥, 라멘' },
    ],
    keywords: ['요리', '쿠킹클래스', '베이킹', '요리학원'],
  },
  {
    id: 'speech-academy',
    name: '스피치학원',
    nameEn: 'Speech Academy',
    category: 'education',
    description: '스피치/발표 학원 소개 페이지',
    icon: '🎤',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '말하기가\n달라집니다',
      subtitle: '발표, 면접, 스피치 전문',
      primaryCTA: { label: '체험 수업', href: '#contact' },
    },
    defaultBusiness: { name: '보이스 스피치', tagline: '발표력 향상 전문' },
    defaultServices: [
      { emoji: '🎤', title: '발표력', description: 'PT, 프레젠테이션' },
      { emoji: '💬', title: '면접', description: '취업/입시 면접' },
      { emoji: '🗣️', title: '보이스', description: '발성, 발음 교정' },
      { emoji: '👥', title: '리더십', description: '회의 진행, 설득' },
    ],
    keywords: ['스피치', '발표', '면접', '화법'],
  },

  // ==================== 추가 뷰티 (7개) ====================
  {
    id: 'eyebrow-shop',
    name: '눈썹문신/반영구',
    nameEn: 'Eyebrow Tattoo',
    category: 'beauty',
    description: '눈썹문신/반영구 샵 소개 페이지',
    icon: '👁️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1588421357574-87938a86fa28?w=1920',
      overlayOpacity: 50,
      title: '자연스러운\n눈썹 완성',
      subtitle: '반영구, 아이라인, 입술 전문',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '뷰티 아이', tagline: '반영구 전문' },
    defaultServices: [
      { emoji: '✨', title: '눈썹', description: '자연눈썹, 콤보' },
      { emoji: '👁️', title: '아이라인', description: '자연, 점막' },
      { emoji: '💋', title: '입술', description: '풀립, 틴트' },
      { emoji: '🌸', title: '헤어라인', description: '헤어라인 교정' },
    ],
    keywords: ['눈썹문신', '반영구', '아이라인', '입술'],
  },
  {
    id: 'waxing-shop',
    name: '왁싱샵',
    nameEn: 'Waxing Shop',
    category: 'beauty',
    description: '왁싱샵 소개 페이지',
    icon: '✨',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '부드럽고\n매끈하게',
      subtitle: '전문 왁싱 서비스',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '스무스 왁싱', tagline: '브라질리언 전문' },
    defaultServices: [
      { emoji: '✨', title: '바디왁싱', description: '다리, 팔, 겨드랑이' },
      { emoji: '💆', title: '페이스', description: '얼굴, 인중' },
      { emoji: '🌟', title: '브라질리언', description: '비키니라인' },
      { emoji: '👨', title: '남성왁싱', description: '가슴, 등, 다리' },
    ],
    keywords: ['왁싱', '제모', '브라질리언', '왁싱샵'],
  },
  {
    id: 'tanning-shop',
    name: '태닝샵',
    nameEn: 'Tanning Salon',
    category: 'beauty',
    description: '태닝샵 소개 페이지',
    icon: '☀️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1531928351158-2f736078e0a1?w=1920',
      overlayOpacity: 50,
      title: '건강한 브론즈\n피부톤',
      subtitle: '안전한 태닝 서비스',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '선샤인 태닝', tagline: '스프레이 태닝 전문' },
    defaultServices: [
      { emoji: '☀️', title: '머신태닝', description: '스탠딩, 베드' },
      { emoji: '🌅', title: '스프레이', description: '에어브러시 태닝' },
      { emoji: '💧', title: '셀프태닝', description: 'DHA 로션' },
      { emoji: '✨', title: '미백', description: '피부 톤 관리' },
    ],
    keywords: ['태닝', '선탠', '브론즈', '피부톤'],
  },
  {
    id: 'barbershop',
    name: '바버샵',
    nameEn: 'Barbershop',
    category: 'beauty',
    description: '남성 전문 바버샵 소개 페이지',
    icon: '💈',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1920',
      overlayOpacity: 50,
      title: '남자의\n스타일을 완성',
      subtitle: '클래식 바버샵',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '젠틀맨 바버', tagline: '남성 헤어 전문' },
    defaultServices: [
      { emoji: '✂️', title: '헤어컷', description: '클래식, 페이드' },
      { emoji: '🪒', title: '쉐이빙', description: '면도, 턱수염' },
      { emoji: '💈', title: '펌', description: '남성 펌' },
      { emoji: '🧴', title: '케어', description: '두피 관리' },
    ],
    keywords: ['바버샵', '남성헤어', '이발소', '면도'],
  },
  {
    id: 'eyelash-shop',
    name: '속눈썹샵',
    nameEn: 'Eyelash Shop',
    category: 'beauty',
    description: '속눈썹 연장/펌 샵 소개 페이지',
    icon: '👁️',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1522849789305-36c39d76ae47?w=1920',
      overlayOpacity: 50,
      title: '눈매의 완성\n속눈썹',
      subtitle: '연장, 펌 전문',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '래쉬 부티크', tagline: '속눈썹 전문' },
    defaultServices: [
      { emoji: '✨', title: '연장', description: '자연, 볼륨, 원포인트' },
      { emoji: '💫', title: '펌', description: '래쉬리프트' },
      { emoji: '🎨', title: '틴팅', description: '속눈썹 염색' },
      { emoji: '🧴', title: '케어', description: '속눈썹 영양' },
    ],
    keywords: ['속눈썹', '래쉬', '연장', '펌'],
  },
  {
    id: 'body-care',
    name: '바디케어/셀룰라이트',
    nameEn: 'Body Care',
    category: 'beauty',
    description: '바디케어/다이어트샵 소개 페이지',
    icon: '💆',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=1920',
      overlayOpacity: 50,
      title: '아름다운 바디라인\n만들기',
      subtitle: '바디케어, 슬리밍 전문',
      primaryCTA: { label: '상담 예약', href: '#contact' },
    },
    defaultBusiness: { name: '슬림뷰티', tagline: '체형관리 전문' },
    defaultServices: [
      { emoji: '💆', title: '슬리밍', description: '셀룰라이트 관리' },
      { emoji: '🔥', title: '체형관리', description: '복부, 허벅지' },
      { emoji: '✨', title: '림프', description: '림프 마사지' },
      { emoji: '🌿', title: '디톡스', description: '독소 배출' },
    ],
    keywords: ['바디케어', '슬리밍', '셀룰라이트', '다이어트'],
  },
  {
    id: 'scalp-care',
    name: '두피케어/탈모관리',
    nameEn: 'Scalp Care',
    category: 'beauty',
    description: '두피케어/탈모관리샵 소개 페이지',
    icon: '💆',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '건강한 모발의 시작\n두피 케어',
      subtitle: '탈모 예방, 두피 관리 전문',
      primaryCTA: { label: '진단 예약', href: '#contact' },
    },
    defaultBusiness: { name: '헤어닥터', tagline: '두피/탈모 전문' },
    defaultServices: [
      { emoji: '💆', title: '두피진단', description: '현미경 정밀 진단' },
      { emoji: '🧴', title: '스케일링', description: '두피 각질 제거' },
      { emoji: '💪', title: '탈모케어', description: '탈모 예방 관리' },
      { emoji: '✨', title: '영양공급', description: '모근 강화' },
    ],
    keywords: ['두피', '탈모', '두피케어', '모발'],
  },

  // ==================== 추가 요식업 (9개) ====================
  {
    id: 'chicken-shop',
    name: '치킨집',
    nameEn: 'Chicken Restaurant',
    category: 'food',
    description: '치킨 전문점 소개 페이지',
    icon: '🍗',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=1920',
      overlayOpacity: 50,
      title: '바삭하고\n맛있는 치킨',
      subtitle: '당일 도축 신선한 닭',
      primaryCTA: { label: '주문하기', href: '#contact' },
    },
    defaultBusiness: { name: '황금치킨', tagline: '수제 양념 전문' },
    defaultServices: [
      { emoji: '🍗', title: '후라이드', description: '바삭한 오리지널', price: '20,000원' },
      { emoji: '🌶️', title: '양념', description: '매콤달콤 양념', price: '21,000원' },
      { emoji: '🧄', title: '간장', description: '달콤 간장', price: '21,000원' },
      { emoji: '🔥', title: '불닭', description: '매운맛 최고', price: '22,000원' },
    ],
    keywords: ['치킨', '후라이드', '양념치킨', '배달'],
  },
  {
    id: 'noodle-shop',
    name: '국수집/면요리',
    nameEn: 'Noodle Restaurant',
    category: 'food',
    description: '국수/면요리 전문점 소개 페이지',
    icon: '🍜',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=1920',
      overlayOpacity: 50,
      title: '정성 가득\n손칼국수',
      subtitle: '매일 반죽하는 쫄깃한 면',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '할머니 칼국수', tagline: '손칼국수 전문' },
    defaultServices: [
      { emoji: '🍜', title: '칼국수', description: '해물, 들깨', price: '9,000원' },
      { emoji: '🥟', title: '만두', description: '손만두, 군만두', price: '7,000원' },
      { emoji: '🍲', title: '수제비', description: '해물 수제비', price: '9,000원' },
      { emoji: '🥡', title: '비빔국수', description: '매콤 비빔', price: '8,000원' },
    ],
    keywords: ['국수', '칼국수', '면요리', '수제비'],
  },
  {
    id: 'dessert-cafe',
    name: '디저트카페',
    nameEn: 'Dessert Cafe',
    category: 'food',
    description: '디저트 카페 소개 페이지',
    icon: '🍰',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=1920',
      overlayOpacity: 40,
      title: '달콤한 순간\n행복한 시간',
      subtitle: '수제 디저트 & 스페셜티 커피',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '스윗 모먼트', tagline: '수제 디저트 전문' },
    defaultServices: [
      { emoji: '🍰', title: '케이크', description: '생크림, 치즈케이크', price: '7,000원~' },
      { emoji: '🧁', title: '마카롱', description: '뚱카롱, 마카롱', price: '3,000원~' },
      { emoji: '🍮', title: '푸딩', description: '카라멜, 밀크티', price: '5,500원' },
      { emoji: '☕', title: '음료', description: '커피, 에이드', price: '5,000원~' },
    ],
    keywords: ['디저트', '카페', '케이크', '마카롱'],
  },
  {
    id: 'chinese-food',
    name: '중식당',
    nameEn: 'Chinese Restaurant',
    category: 'food',
    description: '중식당 소개 페이지',
    icon: '🥢',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=1920',
      overlayOpacity: 50,
      title: '정통 중화요리의\n깊은 맛',
      subtitle: '20년 경력 조리장의 손맛',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '북경반점', tagline: '정통 중화요리' },
    defaultServices: [
      { emoji: '🍜', title: '짜장면', description: '수타 짜장', price: '8,000원' },
      { emoji: '🥡', title: '짬뽕', description: '해물 듬뿍', price: '9,000원' },
      { emoji: '🦐', title: '탕수육', description: '바삭 탕수육', price: '20,000원~' },
      { emoji: '🍚', title: '볶음밥', description: '새우, 잡채', price: '10,000원' },
    ],
    keywords: ['중식', '짜장면', '짬뽕', '중국집'],
  },
  {
    id: 'thai-food',
    name: '태국음식점',
    nameEn: 'Thai Restaurant',
    category: 'food',
    description: '태국 음식점 소개 페이지',
    icon: '🍛',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=1920',
      overlayOpacity: 50,
      title: '태국의 맛을\n그대로',
      subtitle: '정통 타이 요리',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '사와디캅', tagline: '태국 요리 전문' },
    defaultServices: [
      { emoji: '🍜', title: '팟타이', description: '새우 볶음면', price: '13,000원' },
      { emoji: '🍛', title: '똠양꿍', description: '새우 매운탕', price: '15,000원' },
      { emoji: '🥗', title: '솜땀', description: '파파야 샐러드', price: '10,000원' },
      { emoji: '🍚', title: '카오팟', description: '태국 볶음밥', price: '12,000원' },
    ],
    keywords: ['태국', '타이', '팟타이', '똠양꿍'],
  },
  {
    id: 'indian-food',
    name: '인도음식점',
    nameEn: 'Indian Restaurant',
    category: 'food',
    description: '인도 음식점 소개 페이지',
    icon: '🍛',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=1920',
      overlayOpacity: 50,
      title: '향신료의\n마법',
      subtitle: '정통 인도 커리',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '타지마할', tagline: '인도 요리 전문' },
    defaultServices: [
      { emoji: '🍛', title: '커리', description: '치킨, 양고기, 채식', price: '15,000원~' },
      { emoji: '🫓', title: '난', description: '치즈난, 갈릭난', price: '4,000원~' },
      { emoji: '🍢', title: '탄두리', description: '탄두리 치킨', price: '18,000원' },
      { emoji: '🍚', title: '비리야니', description: '인도식 볶음밥', price: '16,000원' },
    ],
    keywords: ['인도', '커리', '탄두리', '난'],
  },
  {
    id: 'vegan-restaurant',
    name: '비건/채식',
    nameEn: 'Vegan Restaurant',
    category: 'food',
    description: '비건/채식 레스토랑 소개 페이지',
    icon: '🥗',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1920',
      overlayOpacity: 40,
      title: '건강하고\n맛있는 채식',
      subtitle: '100% 식물성 요리',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '그린 테이블', tagline: '비건 레스토랑' },
    defaultServices: [
      { emoji: '🥗', title: '샐러드', description: '오가닉 샐러드', price: '12,000원' },
      { emoji: '🍝', title: '파스타', description: '비건 파스타', price: '14,000원' },
      { emoji: '🍔', title: '버거', description: '식물성 버거', price: '13,000원' },
      { emoji: '🍰', title: '디저트', description: '비건 케이크', price: '6,000원' },
    ],
    keywords: ['비건', '채식', '베지테리안', '건강식'],
  },
  {
    id: 'bar-pub',
    name: '바/펍',
    nameEn: 'Bar & Pub',
    category: 'food',
    description: '바/펍 소개 페이지',
    icon: '🍺',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1920',
      overlayOpacity: 60,
      title: '밤을 즐기는\n특별한 공간',
      subtitle: '수제맥주, 칵테일 전문',
      primaryCTA: { label: '메뉴 보기', href: '#menu' },
    },
    defaultBusiness: { name: '더 펍', tagline: '크래프트 비어 전문' },
    defaultServices: [
      { emoji: '🍺', title: '수제맥주', description: 'IPA, 라거, 스타우트', price: '8,000원~' },
      { emoji: '🍸', title: '칵테일', description: '시그니처 칵테일', price: '12,000원~' },
      { emoji: '🥃', title: '위스키', description: '싱글몰트', price: '15,000원~' },
      { emoji: '🍿', title: '안주', description: '피쉬앤칩스, 윙', price: '15,000원~' },
    ],
    keywords: ['바', '펍', '맥주', '칵테일'],
  },
  {
    id: 'food-truck',
    name: '푸드트럭',
    nameEn: 'Food Truck',
    category: 'food',
    description: '푸드트럭 소개 페이지',
    icon: '🚚',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=1920',
      overlayOpacity: 50,
      title: '맛있는 음식이\n찾아갑니다',
      subtitle: '행사/출장 케이터링',
      primaryCTA: { label: '예약하기', href: '#contact' },
    },
    defaultBusiness: { name: '휠스 푸드', tagline: '버거, 타코 전문' },
    defaultServices: [
      { emoji: '🍔', title: '버거', description: '수제 버거', price: '10,000원~' },
      { emoji: '🌮', title: '타코', description: '멕시칸 타코', price: '8,000원~' },
      { emoji: '🍟', title: '사이드', description: '감자튀김, 어니언링', price: '5,000원~' },
      { emoji: '🚚', title: '출장', description: '행사 케이터링', price: '견적 문의' },
    ],
    keywords: ['푸드트럭', '출장', '케이터링', '버거'],
  },

  // ==================== 추가 IT/테크 (6개) ====================
  {
    id: 'web-agency',
    name: '웹에이전시',
    nameEn: 'Web Agency',
    category: 'tech',
    description: '웹 개발/디자인 에이전시 소개 페이지',
    icon: '🌐',
    defaultHero: {
      type: 'gradient',
      overlayOpacity: 30,
      title: '디지털 혁신을\n리드합니다',
      subtitle: '웹사이트, 앱, 브랜딩 전문',
      primaryCTA: { label: '프로젝트 문의', href: '#contact' },
    },
    defaultBusiness: { name: '디지털 스튜디오', tagline: '풀스택 웹 에이전시' },
    defaultServices: [
      { emoji: '🌐', title: '웹사이트', description: '반응형 웹 제작' },
      { emoji: '📱', title: '앱 개발', description: 'iOS, Android' },
      { emoji: '🎨', title: 'UI/UX', description: '디자인 시스템' },
      { emoji: '📈', title: '마케팅', description: 'SEO, 광고' },
    ],
    keywords: ['웹에이전시', '웹개발', '디자인', '앱'],
  },
  {
    id: 'it-consulting',
    name: 'IT컨설팅',
    nameEn: 'IT Consulting',
    category: 'tech',
    description: 'IT 컨설팅 회사 소개 페이지',
    icon: '💻',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '기술로 비즈니스\n문제를 해결합니다',
      subtitle: '클라우드, 보안, 디지털 전환',
      primaryCTA: { label: '상담 신청', href: '#contact' },
    },
    defaultBusiness: { name: '테크 솔루션즈', tagline: 'IT 컨설팅 전문' },
    defaultServices: [
      { emoji: '☁️', title: '클라우드', description: 'AWS, Azure, GCP' },
      { emoji: '🔒', title: '보안', description: '보안 진단, 컨설팅' },
      { emoji: '🔄', title: 'DX', description: '디지털 전환' },
      { emoji: '🤖', title: 'AI', description: 'AI/ML 도입' },
    ],
    keywords: ['IT', '컨설팅', '클라우드', '보안'],
  },
  {
    id: 'seo-agency',
    name: 'SEO/마케팅',
    nameEn: 'SEO Agency',
    category: 'tech',
    description: 'SEO/디지털 마케팅 에이전시 소개 페이지',
    icon: '📈',
    defaultHero: {
      type: 'gradient',
      overlayOpacity: 30,
      title: '검색 상위 노출\n매출 상승',
      subtitle: 'SEO, 광고, SNS 마케팅',
      primaryCTA: { label: '무료 진단', href: '#contact' },
    },
    defaultBusiness: { name: '그로스 마케팅', tagline: '디지털 마케팅 전문' },
    defaultServices: [
      { emoji: '🔍', title: 'SEO', description: '검색엔진 최적화' },
      { emoji: '📢', title: '광고', description: '구글, 네이버, 메타' },
      { emoji: '📱', title: 'SNS', description: '인스타, 유튜브' },
      { emoji: '📊', title: '분석', description: '데이터 분석, 리포트' },
    ],
    keywords: ['SEO', '마케팅', '광고', 'SNS'],
  },
  {
    id: 'video-production',
    name: '영상제작',
    nameEn: 'Video Production',
    category: 'tech',
    description: '영상 제작 스튜디오 소개 페이지',
    icon: '🎬',
    defaultHero: {
      type: 'video',
      backgroundUrl: '/videos/showreel.mp4',
      overlayOpacity: 50,
      title: '영상으로\n스토리를 전달합니다',
      subtitle: '광고, 유튜브, 기업홍보 전문',
      primaryCTA: { label: '제작 문의', href: '#contact' },
    },
    defaultBusiness: { name: '프레임 스튜디오', tagline: '영상 제작 전문' },
    defaultServices: [
      { emoji: '🎬', title: '광고영상', description: 'TVC, 디지털 광고' },
      { emoji: '📹', title: '유튜브', description: '채널 운영, 편집' },
      { emoji: '🏢', title: '기업홍보', description: '홍보, 교육 영상' },
      { emoji: '🎥', title: '촬영', description: '행사, 인터뷰' },
    ],
    keywords: ['영상', '제작', '유튜브', '광고'],
  },
  {
    id: 'game-dev',
    name: '게임개발',
    nameEn: 'Game Development',
    category: 'tech',
    description: '게임 개발사 소개 페이지',
    icon: '🎮',
    defaultHero: {
      type: 'video',
      backgroundUrl: '/videos/game-trailer.mp4',
      overlayOpacity: 50,
      title: '새로운 세계를\n창조합니다',
      subtitle: '모바일, PC 게임 개발',
      primaryCTA: { label: '문의하기', href: '#contact' },
    },
    defaultBusiness: { name: '픽셀 게임즈', tagline: '인디 게임 개발' },
    defaultServices: [
      { emoji: '📱', title: '모바일', description: 'iOS, Android 게임' },
      { emoji: '🖥️', title: 'PC', description: 'Steam 출시' },
      { emoji: '🎨', title: '아트', description: '캐릭터, 배경' },
      { emoji: '🎵', title: '사운드', description: 'BGM, 효과음' },
    ],
    keywords: ['게임', '개발', '인디게임', 'Unity'],
  },
  {
    id: 'ai-service',
    name: 'AI서비스',
    nameEn: 'AI Service',
    category: 'tech',
    description: 'AI 서비스 회사 소개 페이지',
    icon: '🤖',
    defaultHero: {
      type: 'gradient',
      overlayOpacity: 30,
      title: 'AI로 비즈니스를\n혁신합니다',
      subtitle: 'ChatGPT, 이미지 생성, 자동화',
      primaryCTA: { label: '상담 신청', href: '#contact' },
    },
    defaultBusiness: { name: 'AI 솔루션즈', tagline: 'AI 도입 전문' },
    defaultServices: [
      { emoji: '💬', title: '챗봇', description: 'AI 고객상담' },
      { emoji: '📝', title: '콘텐츠', description: 'AI 글쓰기' },
      { emoji: '🖼️', title: '이미지', description: 'AI 이미지 생성' },
      { emoji: '⚙️', title: '자동화', description: '업무 자동화' },
    ],
    keywords: ['AI', '인공지능', '챗봇', '자동화'],
  },

  // ==================== 추가 서비스업 (5개) ====================
  {
    id: 'interior',
    name: '인테리어',
    nameEn: 'Interior Design',
    category: 'service',
    description: '인테리어 업체 소개 페이지',
    icon: '🏠',
    defaultHero: {
      type: 'image',
      backgroundUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1920',
      overlayOpacity: 50,
      title: '공간에 생명을\n불어넣습니다',
      subtitle: '주거, 상업 인테리어 전문',
      primaryCTA: { label: '무료 상담', href: '#contact' },
    },
    defaultBusiness: { name: '스페이스 디자인', tagline: '인테리어 전문' },
    defaultServices: [
      { emoji: '🏠', title: '주거', description: '아파트, 빌라' },
      { emoji: '🏢', title: '상업', description: '카페, 음식점' },
      { emoji: '🏬', title: '오피스', description: '사무실 인테리어' },
      { emoji: '📐', title: '설계', description: '3D 디자인' },
    ],
    keywords: ['인테리어', '리모델링', '공간디자인', '시공'],
  },
  {
    id: 'pest-control',
    name: '방역/해충퇴치',
    nameEn: 'Pest Control',
    category: 'service',
    description: '방역/해충 퇴치 업체 소개 페이지',
    icon: '🐜',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '해충 걱정 없는\n쾌적한 공간',
      subtitle: '친환경 방역 서비스',
      primaryCTA: { label: '출장 신청', href: '#contact' },
    },
    defaultBusiness: { name: '클린 방역', tagline: '해충 퇴치 전문' },
    defaultServices: [
      { emoji: '🐜', title: '개미', description: '개미 완벽 퇴치' },
      { emoji: '🪳', title: '바퀴벌레', description: '독일바퀴 전문' },
      { emoji: '🐭', title: '쥐', description: '쥐 방제' },
      { emoji: '🦟', title: '모기', description: '모기, 파리 방역' },
    ],
    keywords: ['방역', '해충', '바퀴벌레', '개미'],
  },
  {
    id: 'locksmith',
    name: '열쇠/도어락',
    nameEn: 'Locksmith',
    category: 'service',
    description: '열쇠/도어락 업체 소개 페이지',
    icon: '🔐',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '24시간\n긴급 출동',
      subtitle: '열쇠, 도어락, 금고',
      primaryCTA: { label: '긴급 출동', href: '#contact' },
    },
    defaultBusiness: { name: '스피드 열쇠', tagline: '24시 긴급 출동' },
    defaultServices: [
      { emoji: '🔑', title: '열쇠', description: '분실, 복사, 교체' },
      { emoji: '🚪', title: '도어락', description: '설치, AS' },
      { emoji: '🔒', title: '금고', description: '금고 열기' },
      { emoji: '🚗', title: '차량', description: '자동차 열쇠' },
    ],
    keywords: ['열쇠', '도어락', '잠금장치', '긴급'],
  },
  {
    id: 'printing',
    name: '인쇄소/복사점',
    nameEn: 'Print Shop',
    category: 'service',
    description: '인쇄소/복사점 소개 페이지',
    icon: '🖨️',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '품질 높은\n인쇄 서비스',
      subtitle: '명함, 전단지, 책자',
      primaryCTA: { label: '견적 문의', href: '#contact' },
    },
    defaultBusiness: { name: '프린트샵', tagline: '빠른 인쇄 전문' },
    defaultServices: [
      { emoji: '📇', title: '명함', description: '고급 명함', price: '2만원/200장' },
      { emoji: '📄', title: '전단지', description: 'A4, A5', price: '5만원/1000장' },
      { emoji: '📕', title: '책자', description: '무선제본, 스프링', price: '견적 문의' },
      { emoji: '🖼️', title: '대형출력', description: '현수막, 배너', price: '견적 문의' },
    ],
    keywords: ['인쇄', '복사', '명함', '전단지'],
  },
  {
    id: 'delivery',
    name: '퀵서비스/배송',
    nameEn: 'Quick Delivery',
    category: 'service',
    description: '퀵서비스/배송 업체 소개 페이지',
    icon: '🏃',
    defaultHero: {
      type: 'solid',
      overlayOpacity: 0,
      title: '빠르고\n안전한 배송',
      subtitle: '서울/수도권 당일 배송',
      primaryCTA: { label: '배송 신청', href: '#contact' },
    },
    defaultBusiness: { name: '스피드 퀵', tagline: '1시간 내 배송' },
    defaultServices: [
      { emoji: '🏍️', title: '오토바이', description: '서류, 소화물', price: '기본 8,000원' },
      { emoji: '🚐', title: '다마스', description: '중량물, 부피물', price: '기본 25,000원' },
      { emoji: '🚛', title: '1톤트럭', description: '대량 배송', price: '기본 50,000원' },
      { emoji: '📦', title: '정기배송', description: '기업 계약', price: '협의' },
    ],
    keywords: ['퀵', '배송', '퀵서비스', '당일배송'],
  },
]

// 카테고리 정보
export const ONEPAGE_CATEGORIES: Record<OnepageCategory, { name: string; icon: string; description: string }> = {
  professional: { name: '전문직', icon: '⚖️', description: '변호사, 의사, 회계사 등' },
  education: { name: '교육', icon: '📚', description: '학원, 과외, 코칭 등' },
  beauty: { name: '뷰티', icon: '💄', description: '헤어, 네일, 피부 등' },
  food: { name: '요식업', icon: '🍽️', description: '카페, 레스토랑, 베이커리 등' },
  health: { name: '건강/운동', icon: '💪', description: '헬스, 요가, 수영 등' },
  realestate: { name: '부동산', icon: '🏠', description: '중개, 인테리어 등' },
  event: { name: '이벤트', icon: '🎉', description: '웨딩, 촬영, 파티 등' },
  tech: { name: 'IT/테크', icon: '💻', description: '개발, 디자인, 마케팅 등' },
  service: { name: '서비스업', icon: '🔧', description: '청소, 수리, 이사 등' },
  retail: { name: '소매', icon: '🛍️', description: '의류, 잡화, 꽃 등' },
  art: { name: '예술', icon: '🎨', description: '음악, 미술, 공예 등' },
  pet: { name: '반려동물', icon: '🐾', description: '펫샵, 미용, 호텔 등' },
  travel: { name: '여행/숙박', icon: '✈️', description: '펜션, 투어, 렌탈 등' },
  consulting: { name: '컨설팅', icon: '📊', description: '경영, 세무, 법률 등' },
  personal: { name: '개인', icon: '👤', description: '포트폴리오, 이력서 등' },
}
