/**
 * OneSaaS Plugin Registry
 * 플러그인 레지스트리 - 테마, 템플릿, 컴포넌트 관리
 */

import type {
  ThemeId,
  ThemeMeta,
  TemplateMeta,
  TemplateCategory,
} from './types'

// 테마 레지스트리
const themeRegistry = new Map<ThemeId, ThemeMeta>()

// 템플릿 레지스트리
const templateRegistry = new Map<string, TemplateMeta>()

/**
 * 테마 등록
 */
export function registerTheme(theme: ThemeMeta): void {
  themeRegistry.set(theme.id, theme)
}

/**
 * 테마 조회
 */
export function getTheme(id: ThemeId): ThemeMeta | undefined {
  return themeRegistry.get(id)
}

/**
 * 모든 테마 조회
 */
export function getAllThemes(): ThemeMeta[] {
  return Array.from(themeRegistry.values())
}

/**
 * 템플릿 등록
 */
export function registerTemplate(template: TemplateMeta): void {
  templateRegistry.set(template.id, template)
}

/**
 * 템플릿 조회
 */
export function getTemplate(id: string): TemplateMeta | undefined {
  return templateRegistry.get(id)
}

/**
 * 카테고리별 템플릿 조회
 */
export function getTemplatesByCategory(category: TemplateCategory): TemplateMeta[] {
  return Array.from(templateRegistry.values()).filter(
    (template) => template.category === category
  )
}

/**
 * 모든 템플릿 조회
 */
export function getAllTemplates(): TemplateMeta[] {
  return Array.from(templateRegistry.values())
}

/**
 * 기본 테마 정의
 */
export const defaultThemes: ThemeMeta[] = [
  {
    id: 'minimal',
    name: '미니멀',
    nameEn: 'Minimal',
    description: '극도로 절제된 디자인, 생산성 앱에 적합',
    colors: {
      light: {
        bg: '#fafafa',
        bgSecondary: '#f4f4f5',
        text: '#09090b',
        textSecondary: '#71717a',
        accent: '#18181b',
        accentHover: '#27272a',
        border: '#e4e4e7',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#09090b',
        bgSecondary: '#18181b',
        text: '#fafafa',
        textSecondary: '#a1a1aa',
        accent: '#fafafa',
        accentHover: '#e4e4e7',
        border: '#27272a',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Pretendard, -apple-system, sans-serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'small',
    effects: [],
  },
  {
    id: 'neon',
    name: '네온',
    nameEn: 'Neon',
    description: '레트로 퓨처리스틱, AI/테크 스타트업에 적합',
    colors: {
      light: {
        bg: '#fafafa',
        bgSecondary: '#f0fdf4',
        text: '#09090b',
        textSecondary: '#71717a',
        accent: '#00ff88',
        accentHover: '#00cc6a',
        border: '#d1fae5',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#09090b',
        bgSecondary: '#18181b',
        text: '#fafafa',
        textSecondary: '#a1a1aa',
        accent: '#00ff88',
        accentHover: '#00cc6a',
        border: '#27272a',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Space Grotesk, Pretendard, sans-serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'medium',
    effects: ['glow', 'grid'],
  },
  {
    id: 'luxury',
    name: '럭셔리',
    nameEn: 'Luxury',
    description: '고급스러운 디자인, 프리미엄 서비스에 적합',
    colors: {
      light: {
        bg: '#fffbf5',
        bgSecondary: '#fef7ed',
        text: '#1c1917',
        textSecondary: '#78716c',
        accent: '#d4a574',
        accentHover: '#c49561',
        border: '#e7e5e4',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#0c0a09',
        bgSecondary: '#1c1917',
        text: '#fafaf9',
        textSecondary: '#a8a29e',
        accent: '#d4a574',
        accentHover: '#e4b584',
        border: '#292524',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Playfair Display, Noto Serif KR, serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'small',
    effects: ['grain', 'shadow'],
  },
  {
    id: 'playful',
    name: '플레이풀',
    nameEn: 'Playful',
    description: '재미있고 친근한 디자인, 교육/소셜 앱에 적합',
    colors: {
      light: {
        bg: '#fffbeb',
        bgSecondary: '#fef3c7',
        text: '#1c1917',
        textSecondary: '#78716c',
        accent: '#f97316',
        accentHover: '#ea580c',
        border: '#fde68a',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#1c1917',
        bgSecondary: '#292524',
        text: '#fafaf9',
        textSecondary: '#a8a29e',
        accent: '#f97316',
        accentHover: '#fb923c',
        border: '#44403c',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Nunito, Pretendard, sans-serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'full',
    effects: ['gradient'],
  },
  {
    id: 'brutalist',
    name: '브루탈리스트',
    nameEn: 'Brutalist',
    description: '거칠고 강렬한 디자인, 개발자 도구에 적합',
    colors: {
      light: {
        bg: '#ffffff',
        bgSecondary: '#f5f5f5',
        text: '#000000',
        textSecondary: '#525252',
        accent: '#000000',
        accentHover: '#262626',
        border: '#000000',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#000000',
        bgSecondary: '#0a0a0a',
        text: '#ffffff',
        textSecondary: '#a3a3a3',
        accent: '#ffffff',
        accentHover: '#e5e5e5',
        border: '#ffffff',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'JetBrains Mono, monospace',
      body: 'JetBrains Mono, monospace',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'none',
    effects: ['shadow'],
  },
  {
    id: 'corporate',
    name: '코퍼레이트',
    nameEn: 'Corporate',
    description: '전문적이고 신뢰감 있는 디자인, B2B에 적합',
    colors: {
      light: {
        bg: '#ffffff',
        bgSecondary: '#f8fafc',
        text: '#0f172a',
        textSecondary: '#64748b',
        accent: '#2563eb',
        accentHover: '#1d4ed8',
        border: '#e2e8f0',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#0f172a',
        bgSecondary: '#1e293b',
        text: '#f8fafc',
        textSecondary: '#94a3b8',
        accent: '#3b82f6',
        accentHover: '#60a5fa',
        border: '#334155',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Inter, Pretendard, sans-serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'small',
    effects: [],
  },
  {
    id: 'startup',
    name: '스타트업',
    nameEn: 'Startup',
    description: '현대적이고 역동적인 디자인, 스타트업에 적합',
    colors: {
      light: {
        bg: '#ffffff',
        bgSecondary: '#faf5ff',
        text: '#1e1b4b',
        textSecondary: '#6b7280',
        accent: '#8b5cf6',
        accentHover: '#7c3aed',
        border: '#e9d5ff',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#0f0d1a',
        bgSecondary: '#1e1b2e',
        text: '#faf5ff',
        textSecondary: '#a78bfa',
        accent: '#a855f7',
        accentHover: '#c084fc',
        border: '#3b2d5a',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Plus Jakarta Sans, Pretendard, sans-serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'medium',
    effects: ['gradient', 'blur'],
  },
  {
    id: 'fintech',
    name: '핀테크',
    nameEn: 'Fintech',
    description: '신뢰감과 전문성을 주는 디자인, 금융 서비스에 적합',
    colors: {
      light: {
        bg: '#ffffff',
        bgSecondary: '#f0fdfa',
        text: '#042f2e',
        textSecondary: '#5f7470',
        accent: '#0d9488',
        accentHover: '#0f766e',
        border: '#ccfbf1',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#042f2e',
        bgSecondary: '#134e4a',
        text: '#f0fdfa',
        textSecondary: '#99f6e4',
        accent: '#2dd4bf',
        accentHover: '#5eead4',
        border: '#115e59',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'DM Sans, Pretendard, sans-serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'small',
    effects: ['shadow'],
  },
  {
    id: 'healthcare',
    name: '헬스케어',
    nameEn: 'Healthcare',
    description: '청결하고 안정감 있는 디자인, 의료/건강 서비스에 적합',
    colors: {
      light: {
        bg: '#ffffff',
        bgSecondary: '#ecfeff',
        text: '#083344',
        textSecondary: '#64748b',
        accent: '#06b6d4',
        accentHover: '#0891b2',
        border: '#cffafe',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#083344',
        bgSecondary: '#164e63',
        text: '#ecfeff',
        textSecondary: '#a5f3fc',
        accent: '#22d3ee',
        accentHover: '#67e8f9',
        border: '#155e75',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Outfit, Pretendard, sans-serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'medium',
    effects: [],
  },
  {
    id: 'ecommerce',
    name: '이커머스',
    nameEn: 'E-commerce',
    description: '구매 전환에 최적화된 디자인, 쇼핑몰에 적합',
    colors: {
      light: {
        bg: '#ffffff',
        bgSecondary: '#fef2f2',
        text: '#1c1917',
        textSecondary: '#78716c',
        accent: '#e11d48',
        accentHover: '#be123c',
        border: '#fecdd3',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#0c0a09',
        bgSecondary: '#1c1917',
        text: '#fafaf9',
        textSecondary: '#a8a29e',
        accent: '#fb7185',
        accentHover: '#fda4af',
        border: '#292524',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Poppins, Pretendard, sans-serif',
      body: 'Pretendard, -apple-system, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'medium',
    effects: ['shadow', 'gradient'],
  },
  // ========== 특이한 테마 10개 ==========
  {
    id: 'retrowave',
    name: '레트로웨이브',
    nameEn: 'Retrowave',
    description: '80년대 신스웨이브 감성, 네온 핑크와 퍼플',
    colors: {
      light: {
        bg: '#fdf4ff',
        bgSecondary: '#fae8ff',
        text: '#4a044e',
        textSecondary: '#86198f',
        accent: '#d946ef',
        accentHover: '#c026d3',
        border: '#f0abfc',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#0f0015',
        bgSecondary: '#1a0025',
        text: '#fae8ff',
        textSecondary: '#e879f9',
        accent: '#ff00ff',
        accentHover: '#ff44ff',
        border: '#581c87',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Orbitron, Pretendard, sans-serif',
      body: 'Rajdhani, Pretendard, sans-serif',
      mono: 'Share Tech Mono, monospace',
    },
    borderRadius: 'none',
    effects: ['glow', 'grid'],
  },
  {
    id: 'cyberpunk',
    name: '사이버펑크',
    nameEn: 'Cyberpunk',
    description: '디스토피아 미래, 시안과 마젠타의 충돌',
    colors: {
      light: {
        bg: '#f0fdfa',
        bgSecondary: '#ccfbf1',
        text: '#042f2e',
        textSecondary: '#0f766e',
        accent: '#06b6d4',
        accentHover: '#0891b2',
        border: '#5eead4',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#020617',
        bgSecondary: '#0c1222',
        text: '#00ffff',
        textSecondary: '#67e8f9',
        accent: '#ff0080',
        accentHover: '#ff44a4',
        border: '#164e63',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Audiowide, Pretendard, sans-serif',
      body: 'Exo 2, Pretendard, sans-serif',
      mono: 'Fira Code, monospace',
    },
    borderRadius: 'small',
    effects: ['glow', 'blur', 'grid'],
  },
  {
    id: 'aurora',
    name: '오로라',
    nameEn: 'Aurora',
    description: '북극의 신비로운 오로라, 그라데이션 효과',
    colors: {
      light: {
        bg: '#f0fdf4',
        bgSecondary: '#dcfce7',
        text: '#14532d',
        textSecondary: '#166534',
        accent: '#4ade80',
        accentHover: '#22c55e',
        border: '#86efac',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#001a0f',
        bgSecondary: '#002d19',
        text: '#a7f3d0',
        textSecondary: '#6ee7b7',
        accent: '#10b981',
        accentHover: '#34d399',
        border: '#064e3b',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#38bdf8',
      },
    },
    fonts: {
      display: 'Quicksand, Pretendard, sans-serif',
      body: 'Nunito Sans, Pretendard, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'large',
    effects: ['gradient', 'blur', 'glow'],
  },
  {
    id: 'tokyo',
    name: '도쿄 나이트',
    nameEn: 'Tokyo Night',
    description: '일본 도시의 밤거리, 네온사인 분위기',
    colors: {
      light: {
        bg: '#fefce8',
        bgSecondary: '#fef9c3',
        text: '#422006',
        textSecondary: '#854d0e',
        accent: '#facc15',
        accentHover: '#eab308',
        border: '#fde047',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#1a1b26',
        bgSecondary: '#24283b',
        text: '#c0caf5',
        textSecondary: '#9aa5ce',
        accent: '#ff9e64',
        accentHover: '#ffb088',
        border: '#3b4261',
        success: '#9ece6a',
        warning: '#e0af68',
        error: '#f7768e',
        info: '#7aa2f7',
      },
    },
    fonts: {
      display: 'M PLUS Rounded 1c, Pretendard, sans-serif',
      body: 'Noto Sans JP, Pretendard, sans-serif',
      mono: 'Source Code Pro, monospace',
    },
    borderRadius: 'medium',
    effects: ['glow', 'shadow'],
  },
  {
    id: 'forest',
    name: '포레스트',
    nameEn: 'Forest',
    description: '깊은 숲속의 자연 감성, 유기적인 디자인',
    colors: {
      light: {
        bg: '#faf5f0',
        bgSecondary: '#f0ebe3',
        text: '#3d2914',
        textSecondary: '#6b5344',
        accent: '#5c8a4d',
        accentHover: '#4a7040',
        border: '#d4c4b0',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#0d1f0d',
        bgSecondary: '#1a2e1a',
        text: '#d4e4c8',
        textSecondary: '#a3b899',
        accent: '#7cb668',
        accentHover: '#9aca88',
        border: '#2d4a2d',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Fraunces, Noto Serif KR, serif',
      body: 'Source Sans Pro, Pretendard, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'medium',
    effects: ['grain', 'shadow'],
  },
  {
    id: 'ocean',
    name: '딥 오션',
    nameEn: 'Deep Ocean',
    description: '깊은 바다의 신비로움, 푸른 심해 감성',
    colors: {
      light: {
        bg: '#f0f9ff',
        bgSecondary: '#e0f2fe',
        text: '#0c4a6e',
        textSecondary: '#0369a1',
        accent: '#0ea5e9',
        accentHover: '#0284c7',
        border: '#7dd3fc',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#001020',
        bgSecondary: '#001830',
        text: '#bae6fd',
        textSecondary: '#7dd3fc',
        accent: '#38bdf8',
        accentHover: '#0ea5e9',
        border: '#0c4a6e',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
    },
    fonts: {
      display: 'Josefin Sans, Pretendard, sans-serif',
      body: 'Lato, Pretendard, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'large',
    effects: ['blur', 'gradient'],
  },
  {
    id: 'sunset',
    name: '선셋',
    nameEn: 'Sunset',
    description: '노을빛 그라데이션, 따뜻한 오렌지/레드',
    colors: {
      light: {
        bg: '#fffbeb',
        bgSecondary: '#fef3c7',
        text: '#78350f',
        textSecondary: '#92400e',
        accent: '#f97316',
        accentHover: '#ea580c',
        border: '#fdba74',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#1c0a00',
        bgSecondary: '#2d1200',
        text: '#fed7aa',
        textSecondary: '#fdba74',
        accent: '#fb923c',
        accentHover: '#f97316',
        border: '#7c2d12',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#f87171',
        info: '#38bdf8',
      },
    },
    fonts: {
      display: 'Righteous, Pretendard, sans-serif',
      body: 'Rubik, Pretendard, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    borderRadius: 'full',
    effects: ['gradient', 'glow'],
  },
  {
    id: 'space',
    name: '스페이스',
    nameEn: 'Space',
    description: '우주의 신비, 은하수와 별빛',
    colors: {
      light: {
        bg: '#faf5ff',
        bgSecondary: '#f3e8ff',
        text: '#3b0764',
        textSecondary: '#6b21a8',
        accent: '#a855f7',
        accentHover: '#9333ea',
        border: '#d8b4fe',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#0a0014',
        bgSecondary: '#150025',
        text: '#e9d5ff',
        textSecondary: '#c4b5fd',
        accent: '#a855f7',
        accentHover: '#c084fc',
        border: '#4c1d95',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#f87171',
        info: '#60a5fa',
      },
    },
    fonts: {
      display: 'Oxanium, Pretendard, sans-serif',
      body: 'Space Grotesk, Pretendard, sans-serif',
      mono: 'Space Mono, monospace',
    },
    borderRadius: 'medium',
    effects: ['glow', 'blur', 'gradient'],
  },
  {
    id: 'candy',
    name: '캔디',
    nameEn: 'Candy',
    description: '달콤한 파스텔 컬러, 귀여운 디자인',
    colors: {
      light: {
        bg: '#fff1f2',
        bgSecondary: '#ffe4e6',
        text: '#9f1239',
        textSecondary: '#be123c',
        accent: '#fb7185',
        accentHover: '#f43f5e',
        border: '#fda4af',
        success: '#4ade80',
        warning: '#fbbf24',
        error: '#f87171',
        info: '#60a5fa',
      },
      dark: {
        bg: '#2d0a14',
        bgSecondary: '#3d0f1c',
        text: '#fecdd3',
        textSecondary: '#fda4af',
        accent: '#f472b6',
        accentHover: '#f9a8d4',
        border: '#881337',
        success: '#4ade80',
        warning: '#fbbf24',
        error: '#f87171',
        info: '#60a5fa',
      },
    },
    fonts: {
      display: 'Fredoka One, Pretendard, sans-serif',
      body: 'Nunito, Pretendard, sans-serif',
      mono: 'Fira Code, monospace',
    },
    borderRadius: 'full',
    effects: ['gradient'],
  },
  {
    id: 'terminal',
    name: '터미널',
    nameEn: 'Terminal',
    description: 'CRT 모니터 감성, 레트로 해커 스타일',
    colors: {
      light: {
        bg: '#f4f4f5',
        bgSecondary: '#e4e4e7',
        text: '#18181b',
        textSecondary: '#3f3f46',
        accent: '#16a34a',
        accentHover: '#15803d',
        border: '#d4d4d8',
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
      },
      dark: {
        bg: '#000000',
        bgSecondary: '#0a0a0a',
        text: '#00ff00',
        textSecondary: '#22c55e',
        accent: '#00ff00',
        accentHover: '#4ade80',
        border: '#1a1a1a',
        success: '#00ff00',
        warning: '#facc15',
        error: '#ff0000',
        info: '#00ffff',
      },
    },
    fonts: {
      display: 'VT323, monospace',
      body: 'Fira Code, monospace',
      mono: 'Fira Code, monospace',
    },
    borderRadius: 'none',
    effects: ['glow', 'grid'],
  },
]

// 기본 테마 등록
defaultThemes.forEach(registerTheme)

export { themeRegistry, templateRegistry }
